import { SiteContent } from '../types';

export const europeContent: SiteContent = {
  meta: {
    id: 'europe',
    name: 'High-Pressure-Steam Inspection',
    shortName: 'High-Pressure-Steam Inspection',
    tagline: 'Statutory compliance, PED Category IV mandatory inspection rules, 2-litre threshold, and TCO analysis for professional high-pressure steam trailers across Europe',
    domain: 'highpressuresteaminspection.eu',
    baseUrl: 'https://www.highpressuresteaminspection.eu',
    language: 'en',
    currency: '€',
    legalDisclaimer: 'This technical knowledge platform provides objective regulatory and engineering intelligence based on European Directive 2014/68/EU (PED) and national in-service frameworks (BetrSichV, Arrêté 2017, WBDA, Codex, PSSR 2000). No legal rights can be derived from the calculations or recommendations.',
    copyrightHolder: 'High-Pressure-Steam Inspection',
  },
  navItems: [
    {
      id: 'home',
      label: 'Home',
      slug: '/',
      shortTitle: 'Home',
      seoTitle: 'High-Pressure-Steam Inspection | PED 2014/68/EU Compliance',
      seoDescription: 'Independent technical guide on legal frameworks, PED Category IV inspection obligations, 2-litre threshold, and lifecycle TCO for high-pressure hot water and steam trailers across Europe.',
    },
    {
      id: 'wbda-2016',
      label: 'PED Directive & Law',
      slug: '/ped-directive-2014-68-eu',
      shortTitle: 'Trailer Directives',
      seoTitle: 'High-Pressure Trailers & PED 2014/68/EU: In-Service Rules Explained | High-Pressure-Steam Inspection',
      seoDescription: 'Comprehensive breakdown of Directive 2014/68/EU, manufacturing conformity vs. national in-service regulations, Notified Bodies, and why dealers rarely disclose mandatory recertification.',
    },
    {
      id: 'two-liter-grens',
      label: 'The 2-Litre Threshold',
      slug: '/2-litre-threshold-ped',
      shortTitle: '2-Litre Threshold',
      seoTitle: 'The 2-Litre Threshold in High-Pressure Trailers: SEP vs. Category IV | High-Pressure-Steam Inspection',
      seoDescription: 'Why a 2-litre heating coil volume in steam trailers marks the legal boundary between Sound Engineering Practice (SEP) and heavy Category IV statutory inspections.',
    },
    {
      id: 'keuringsverplichtingen',
      label: 'Inspection Guide',
      slug: '/in-service-inspection-guide',
      shortTitle: 'Inspection Guide',
      seoTitle: 'Trailer Inspection Guide: Pre-Commissioning Audits & Spare Parts Lock-in | High-Pressure-Steam Inspection',
      seoDescription: 'Practical guide to pre-commissioning inspections, mandatory biennial recertification, and the strict prohibition of universal hoses on Category IV high-pressure trailers.',
    },
    {
      id: 'internationaal',
      label: 'EU Member States',
      slug: '/eu-member-state-regulations',
      shortTitle: 'EU Member States',
      seoTitle: 'Trailer In-Service Rules Across EU Member States (DE, FR, NL, BE, UK) | High-Pressure-Steam Inspection',
      seoDescription: 'Country-by-country comparison for operating high-pressure trailers: Germany (BetrSichV), France (Arrêté 2017), Netherlands (WBDA), Belgium (Codex), and UK (PSSR 2000).',
    },
    {
      id: 'tco-calculator',
      label: 'TCO Calculator',
      slug: '/tco-inspection-cost-calculator',
      shortTitle: 'TCO Calculator',
      seoTitle: 'High-Pressure Trailer TCO Calculator: Lifecycle Inspection & Downtime Costs | High-Pressure-Steam Inspection',
      seoDescription: 'Calculate the 10-year Total Cost of Ownership for high-pressure trailers including initial commissioning audits, biennial inspections, downtime loss, and OEM spare parts markup.',
    },
    {
      id: 'downloadcenter',
      label: 'Checklist Download',
      slug: '/download-procurement-checklist',
      shortTitle: 'Checklist',
      seoTitle: 'Download High-Pressure Trailer Procurement & Audit Checklist (PDF) | High-Pressure-Steam Inspection',
      seoDescription: 'Actionable procurement and compliance checklist with 10 critical verification questions every fleet manager and buyer must ask the trailer dealer prior to purchase.',
    },
    {
      id: 'faq',
      label: 'FAQ',
      slug: '/frequently-asked-questions',
      shortTitle: 'FAQ',
      seoTitle: 'Frequently Asked Questions: High-Pressure Trailer PED Compliance & Audits | High-Pressure-Steam Inspection',
      seoDescription: 'Answers to the top legal and technical questions on steam trailer volume thresholds, Notified Bodies, vendor lock-in, shutdown sanctions, and sales disclosures.',
    },
  ],
  hero: {
    badge: 'European Regulatory Standard: PED 2014/68/EU • EN 12952 • In-Service Frameworks',
    title: 'High-Pressure Steam Trailers,',
    titleHighlight: 'The Hidden Inspection Mandate & TCO',
    description: 'Does the high-pressure trailer have a burner or heat exchanger capacity exceeding 2 litres at > 110 °C? Under European law, this qualifies as a PED Category IV steam generator: an initial Commissioning Inspection (KvI) by an authorized Notified Body or accredited inspection service (e.g., TÜV, Dekra, Kiwa, Vinçotte) and periodic (biennial*) recertifications are legally mandatory. If the volume remains below 2 litres (SEP / Sound Engineering Practice), the trailer is completely exempt from these statutory inspections.',
    footnote: '* Inspection intervals vary by member state (e.g. 24 months in the Netherlands under WBDA 2016, whereas Belgian Codex mandates annual recertification by default unless explicitly licensed otherwise).',
    ctaCalculator: 'Calculate Trailer Lifecycle TCO',
    ctaWizard: 'Check Your High-Pressure Trailer',
    stats: [
      {
        value: '2 Litres',
        label: 'Burner/Heat Exchanger Threshold',
        sublabel: 'SEP vs. Cat. IV Mandatory Audits',
      },
      {
        value: '24 Months*',
        label: 'Recertification Cycle',
        sublabel: 'National bodies (varies by member state)*',
      },
      {
        value: '€ 18,500+',
        label: 'TCO Variance per High-Pressure Trailer',
        sublabel: 'Audits, downtime & parts lock-in',
      },
    ],
  },
  wizard: {
    badge: 'Interactive Trailer Decision Tree',
    title: 'Is Your High-Pressure Trailer Subject to Mandatory Statutory Audits?',
    subtitle: 'Answer 3 straightforward technical questions regarding the operating parameters of your mobile steam trailer or skid to establish its exact legal status under European regulations.',
    openButtonText: 'Start Direct Trailer Assessment',
    stepIndicator: 'Step {step} of {total}',
    questions: {
      q1: {
        title: 'What are the maximum pressure (PS) and water temperature (TS) of your high-pressure trailer?',
        description: 'The European Pressure Equipment Directive sets specific regulatory thresholds for superheated water and steam (> 110 °C).',
        optA_title: 'Hot Water & Steam (> 31.25 bar AND > 110 °C)',
        optA_desc: 'Standard for professional high-pressure hot water/steam trailers (facade cleaning, gum removal, industrial sanitisation, weed control).',
        optB_title: 'Cold Water or Low Pressure (≤ 31.25 bar OR ≤ 110 °C)',
        optB_desc: 'Cold-water high-pressure trailers or units operating strictly below the boiling point of 110 °C.',
      },
      q2: {
        title: 'What is the internal fluid volume (V) of the burner/heat exchanger in the high-pressure trailer?',
        description: 'Under PED 2014/68/EU Annex II Table 5, the physical internal fluid capacity dictates whether the machine qualifies as Sound Engineering Practice or Category IV.',
        optA_title: 'Strictly 2 litres or less (V ≤ 2 L)',
        optA_desc: 'Compact continuous-flow mono-tube coil with an internal water volume of 2 litres or lower.',
        optB_title: 'Greater than 2 litres (V > 2 L)',
        optB_desc: 'Traditional burner/heat exchanger coil or boiler holding more than 2 litres of water (typically 3 to 15 litres).',
      },
      q3: {
        title: 'Does the complete high-pressure trailer carry a PED Category IV Assembly Certificate with a 4-digit NoBo number?',
        description: 'Inspect the identification nameplate of the complete high-pressure trailer for a 4-digit Notified Body identification number (e.g., 0036 TÜV, 0029 Apragaz, 0620 Kiwa).',
        optA_title: 'Yes, CE with 4-digit NoBo number (Cat. IV Assembly)',
        optA_desc: 'The manufacturer certified the entire high-pressure trailer as a Category IV assembly and provides an official EU Declaration of Conformity.',
        optB_title: 'No / No 4-digit NoBo number (Generic CE only)',
        optB_desc: 'The high-pressure trailer only displays generic Machinery Directive CE or a CE mark on the burner/heat exchanger alone, with NO PED Category IV assembly certificate.',
      },
    },
    results: {
      green_sep: {
        title: 'Inspection-Exempt High-Pressure Trailer under Sound Engineering Practice (SEP / Art. 4.3)',
        subtitle: 'No mandatory commissioning inspection and no statutory periodic audits across Europe',
        summary: 'Because the fluid volume inside the burner/heat exchanger is strictly 2 litres or less, this high-pressure trailer qualifies under Article 4, Paragraph 3 of Directive 2014/68/EU (Sound Engineering Practice).',
        bullets: [
          'Exempt from mandatory pre-commissioning inspections by third-party inspection bodies across the EU.',
          'No statutory periodic recertification cycles (biennial)*, hydraulic pressure tests, or mandatory fleet downtime.',
          'Complete freedom in spare parts procurement: you may source certified universal high-pressure hoses, nozzles, and spray triggers without voiding compliance.',
          'Significantly lower 10-year Total Cost of Ownership and frictionless cross-border fleet deployment.',
          'Standard operational occupational safety and engine/chassis roadworthiness maintenance remain applicable.',
        ],
      },
      exempt: {
        title: 'Below High-Pressure Steam Threshold',
        subtitle: 'Not subject to heavy steam boiler regulations',
        summary: 'Operating below 31.25 bar or 110 °C places the high-pressure trailer outside the highest-risk European steam boiler classification.',
        bullets: [
          'No statutory Category IV inspection regime required.',
          'Standard European Machinery Directive (2006/42/EC) maintenance guidelines apply.',
        ],
      },
      red_ped4: {
        title: 'Statutory Inspection Mandatory: PED Category IV High-Pressure Trailer',
        subtitle: 'Stringent operational inspection obligations across all EU Member States',
        summary: 'With an internal burner/heat exchanger volume > 2 litres at > 110 °C, this high-pressure trailer legally represents a mobile steam boiler under PED Category IV.',
        bullets: [
          'Pre-commissioning inspection mandatory by an accredited national body (e.g., TÜV, Dekra, Vinçotte, APAVE) before first operational deployment on road or site.',
          'Mandatory periodic recertification (every 24 months*, or annually in Belgium) including safety relief valve pop-testing and wall-thickness audits.',
          'Strict spare parts lock-in: replacing hoses or relief valves with universal components immediately invalidates the assembly certificate.',
          'Operating uninspected equipment constitutes a regulatory offence triggering immediate shutdown orders by labour inspectorates and voided insurance coverage.',
          'Substantial cumulative operational expense in audit fees, logistics, and mandatory team downtime.',
        ],
      },
      critical_violation: {
        title: 'CRITICAL REGULATORY VIOLATION: Illegal High-Pressure Trailer',
        subtitle: 'Severe employer liability exposure and imminent safety hazard',
        summary: 'The high-pressure trailer exceeds 2 litres at > 110 °C but lacks mandatory PED Category IV assembly certification under Notified Body oversight.',
        bullets: [
          'This machine cannot legally be placed on the European market or operated in public spaces.',
          'Operation constitutes an immediate violation of European occupational safety directives and national law.',
          'Commercial liability and property insurance policies are completely nullified in the event of rupture, scalding, or fire.',
          'Contact the trailer vendor immediately for formal clarification, rectification, or purchase cancellation.',
        ],
      },
    },
  },
  tco: {
    title: 'Total Cost of Ownership (TCO) Calculator for High-Pressure Trailers',
    subtitle: 'Evaluate the true 10-year lifecycle cost: Category IV High-Pressure Trailer vs. Inspection-Exempt (< 2 Litres)',
    calculatorTitle: 'Interactive High-Pressure Trailer TCO Comparative Model',
    description: 'Calculate cumulative financial variances per high-pressure trailer including initial commissioning audits, biennial recertifications, crew downtime loss, and OEM proprietary spare parts markup.',
    defaults: {
      machineCount: 1,
      years: 10,
      kviCostPerMachine: 1250,
      periodicInspectionCost: 1150,
      downtimeDaysPerKeuring: 2,
      downtimeCostPerDay: 650,
      partsCostDifferenceAnnual: 750,
      inspectionIntervalMonths: 24,
    },
    labels: {
      machineCount: 'Number of high-pressure trailers in fleet',
      years: 'Operating lifecycle (years)',
      initialInspection: 'Pre-commissioning inspection cost per high-pressure trailer',
      periodicInspection: 'Statutory recertification audit (every 24 months* per high-pressure trailer)',
      downtimeDays: 'Operational downtime days per audit (hydrostatic testing, transport, audit)',
      downtimeCost: 'Labour crew and lost revenue cost per high-pressure trailer downtime day',
      partsMarkup: 'Annual proprietary parts markup (OEM certified hoses, valves, triggers)',
      totalSavingsTitle: 'Total savings with Inspection-Exempt High-Pressure Trailer (SEP < 2L)',
      totalCat4CostTitle: 'Total lifecycle cost for Category IV High-Pressure Trailer Assembly',
      totalSepCostTitle: 'Total lifecycle cost for SEP (< 2L) High-Pressure Trailer',
    },
  },
  faq: [
    {
      id: 'faq-1',
      category: 'Directives',
      question: 'What is the scope of European Directive 2014/68/EU (PED)?',
      answer: 'The Pressure Equipment Directive (PED 2014/68/EU) harmonizes European legislation on the design, manufacture, and conformity assessment of pressure equipment and assemblies with a maximum allowable pressure greater than 0.5 bar. It applies to equipment placed on the European market, establishing safety categories from I to IV.',
    },
    {
      id: 'faq-2',
      category: 'Engineering',
      question: 'What is the 2-litre threshold under PED Annex II Table 5?',
      answer: 'Under PED 2014/68/EU Annex II Table 5 (fired or heated pressure equipment for steam or superheated water > 110 °C and > 31.25 bar), equipment with a burner/heat exchanger volume up to 2 litres falls under Article 4(3) Sound Engineering Practice (SEP). Exceeding 2 litres automatically elevates the entire high-pressure trailer assembly into the highest hazard tier: Category IV.',
    },
    {
      id: 'faq-3',
      category: 'Inspections',
      question: 'What is a Pre-Commissioning Inspection?',
      answer: 'A pre-commissioning inspection is a statutory on-site verification performed by a nationally accredited inspection body (such as TÜV in Germany, Dekra in the Netherlands, Vinçotte in Belgium, or APAVE in France) before a Category IV pressure installation is permitted to enter operational service.',
    },
    {
      id: 'faq-4',
      category: 'Inspections',
      question: 'How frequently must a Category IV high-pressure trailer be reinspected?',
      answer: 'While in-service inspection intervals are set by individual EU Member State national legislation, the general European standard for high-temperature steam and hot water units is every 24 months (2 years)*. However, this interval varies by country: for example, in the Netherlands a 24-month cycle applies under WBDA 2016, in Belgium an annual recertification (every 12 months) is mandatory under the Codex, in Germany intervals range between 1 and 3 years under BetrSichV, and in specific circumstances manufacturers or inspection bodies may stipulate differing inspection terms.',
    },
    {
      id: 'faq-5',
      category: 'Spare Parts & Lock-in',
      question: 'Why is using universal high-pressure hoses prohibited on Category IV high-pressure trailers?',
      answer: 'When a high-pressure trailer is certified as an integrated Category IV assembly under Notified Body oversight, the type-approval strictly encompasses the certified OEM burst-rated hoses and safety relief valves. Replacing a worn hose with a generic universal hydraulic hose legally constitutes an unauthorised modification under Directive 2014/68/EU. The assembly CE certificate is immediately nullified, rendering the high-pressure trailer illegal in operation and voiding commercial insurance indemnity.',
    },
    {
      id: 'faq-6',
      category: 'Enforcement & Sanctions',
      question: 'What penalties apply for operating an uninspected high-pressure trailer in Europe?',
      answer: 'National labour and health & safety inspectorates across the EU actively audit contractors performing facade, graffiti, and industrial surface cleaning. Operating an uninspected Category IV high-pressure trailer constitutes an administrative and criminal workplace safety violation. Penalties include immediate stop-work orders (sealing the high-pressure trailer on-site), substantial fines running into tens of thousands of euros, and complete nullification of liability insurance.',
    },
    {
      id: 'faq-7',
      category: 'Directives',
      question: 'Does the statutory inspection requirement apply if the high-pressure trailer already carries a CE mark?',
      answer: 'Yes, unconditionally. A manufacturer CE mark confirms compliance solely with European manufacturing directives at the factory gate. Once the high-pressure trailer is commissioned and operated on public roads or client facilities, national European in-service health and safety legislation governs mandatory pre-commissioning examinations and periodic recertifications (typically biennial)*.',
    },
    {
      id: 'faq-8',
      category: 'Procurement Disclosures',
      question: 'Why do equipment dealers rarely disclose that periodic recertification is legally required?',
      answer: 'Sales representatives focus heavily on operational specifications such as working pressure (e.g. 350–500 bar), engine power, and cleaning speed. Mandatory in-service inspection requirements are frequently omitted because dealers fear prospective buyers will balk at € 1,250 commissioning fees, recurring periodic audits (every 24 months)*, and mandatory downtime. Furthermore, mandatory OEM replacement hoses represent a lucrative ongoing aftersales revenue stream for traditional dealers.',
    },
    {
      id: 'faq-9',
      category: 'Inspectors',
      question: 'Who is legally authorized to inspect a Category IV high-pressure trailer in Europe?',
      answer: 'In-service inspections must be carried out by nationally accredited inspection organizations (e.g. ZÜS such as TÜV or Dekra in Germany, NL-CBI in the Netherlands, EDTC in Belgium, and Organismes Agréés in France and Luxembourg). Standard vehicle roadworthiness checks (chassis MOT/APK/TÜV) do NOT satisfy the statutory inspection obligations for the high-pressure steam boiler assembly.',
    },
    {
      id: 'faq-10',
      category: 'Fleet & Rental',
      question: 'Does the inspection obligation apply when leasing or renting a high-pressure trailer?',
      answer: 'Yes, without exception. Under European workplace safety framework directives, every employer providing work equipment to personnel is strictly liable for ensuring it is fully verified and compliant. When renting or leasing a high-pressure steam trailer, operators must verify that the valid pre-commissioning sign-off and current periodic inspection certificate are physically present in the on-board documentation dossier.',
    },
  ],
  checklist: [
    {
      id: 'chk-1',
      phase: 'Procurement & Quotation',
      title: 'Demand written confirmation of burner/heat exchanger internal volume (V)',
      description: 'Request formal documentation from the high-pressure trailer OEM specifying the exact fluid volume (V) of the burner/heat exchanger in litres. Is it strictly ≤ 2 litres (SEP inspection-exempt) or > 2 litres (Category IV mandatory inspection)?',
      requirement: 'Art. 4.3 SEP vs. PED Category IV',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-2',
      phase: 'Procurement & Quotation',
      title: 'Establish high-pressure trailer design pressure (PS) and temperature (TS)',
      description: 'Confirm whether maximum allowable pressure (e.g. 200–500 bar) and operating temperature (> 110 °C superheated water/steam) trigger European boiler classification.',
      requirement: 'PED 2014/68/EU Annex II Table 5',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-3',
      phase: 'Procurement & Quotation',
      title: 'Verify spare parts policy and vendor lock-in terms for hoses',
      description: 'Obtain written confirmation whether high-pressure hoses, nozzles, and spray lances can be replaced with certified universal components without voiding the assembly certificate.',
      requirement: 'Assembly Technical File & Vendor Lock-in Risk',
      criticality: 'Critical Check',
    },
    {
      id: 'chk-4',
      phase: 'Procurement & Quotation',
      title: 'Budget periodic statutory audits (24 months)* and operational downtime',
      description: 'If procuring a high-pressure trailer with a burner/heat exchanger volume > 2 litres, immediately include periodic recertification costs (approx. € 1,150 every 24 months*) and 2 days of crew downtime in fleet operational budgets. *Interval may vary by member state.',
      requirement: 'TCO Fleet Lifecycle Budgeting',
      criticality: 'Recommended',
    },
    {
      id: 'chk-5',
      phase: 'Trailer Delivery',
      title: 'Verify high-pressure trailer identification nameplate (CE + 4-digit NoBo number)',
      description: 'For Category IV high-pressure trailers, verify that the 4-digit identification number of the certifying Notified Body (e.g. 0036, 0029, 0620) is stamped directly on the main assembly nameplate.',
      requirement: 'PED 2014/68/EU Art. 19 Nameplate Standards',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-6',
      phase: 'Trailer Delivery',
      title: 'Require EU Declaration of Conformity for the entire high-pressure trailer assembly',
      description: 'Demand the official EU Declaration of Conformity certifying the complete high-pressure trailer as a Category IV assembly, and refuse delivery if only individual certificates for pump or burner/heat exchanger are provided.',
      requirement: 'PED 2014/68/EU Module G or B+D/F Assembly Dossier',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-7',
      phase: 'Prior to First Job',
      title: 'Execute on-site pre-commissioning audit by accredited body',
      description: 'For high-pressure trailers exceeding 2 litres burner/heat exchanger volume, contract an accredited inspection body (TÜV, Dekra, Vinçotte, APAVE) for statutory commissioning sign-off prior to the first operational job on road or site.',
      requirement: 'National In-Service Frameworks (BetrSichV, WBDA, Codex)',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-8',
      phase: 'Prior to First Job',
      title: 'Verify safety relief valve, rupture disc, and thermal cutouts',
      description: 'Confirm the tamper-evident seal on the safety relief valve and test automatic burner/heat exchanger shutoff triggers under water deficiency or over-pressure in accordance with EN 12952.',
      requirement: 'EN 12952 / European Safety Interlock Norms',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-9',
      phase: 'Fleet Management',
      title: 'Maintain physical audit dossier on-board the high-pressure trailer',
      description: 'Equip the high-pressure trailer with a weatherproof documentation tube containing the initial Commissioning Certificate and current recertification report for workplace safety audits.',
      requirement: 'Statutory Recordkeeping & Inspectorate Burden of Proof',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-10',
      phase: 'Fleet Management',
      title: 'Schedule periodic recertification (24 months)* in fleet maintenance schedule',
      description: 'Schedule the periodic statutory inspection with an accredited body at least 60 days before the recertification deadline (*typically 24 months, or annually in Belgium/local mandates) to avoid uninspected operation and regulatory shutdown.',
      requirement: 'Periodic Recertification Standards',
      criticality: 'Mandatory',
    },
  ],
  common: {
    readMore: 'Read Full Technical Briefing',
    downloadGuide: 'Download PDF Knowledge Guide',
    openDecisionTree: 'Open Compliance Check',
    calculateTco: 'Go to TCO Calculator',
    contactNote: 'Do you have specific compliance or engineering questions regarding your fleet?',
    sourceReferences: 'Official sources: European Directive 2014/68/EU (PED), EN 12952 / EN 13445 Standards, German BetrSichV, French Arrêté 2017, Dutch WBDA 2016, Belgian Codex.',
    legalNotice: 'No legal rights may be derived from the contents of this technical platform. Always consult an accredited national inspection authority for formal determinations.',
  },
};
