import { SiteContent } from '../types';

export const beneluxContentDe: SiteContent = {
  meta: {
    id: 'benelux',
    name: 'Hochdrucktrailer Prüfung',
    shortName: 'Hochdrucktrailer Prüfung',
    tagline: 'Gesetzliche Rahmenbedingungen, Prüfpflicht nach DGRL Kategorie IV, 2-Liter-Grenze und TCO-Analyse für Heißwasser- und Dampf-Hochdrucktrailer in Luxemburg, Belgien und den Niederlanden',
    domain: 'www.hogedruktrailerkeuren.eu',
    baseUrl: 'https://www.hogedruktrailerkeuren.eu',
    language: 'de-LU',
    currency: '€',
    legalDisclaimer: 'Diese unabhängige Wissensplattform bietet objektive technische und rechtliche Aufklärung auf Basis geltender Vorschriften (LU: ITM / BE: Codex Wohlbefinden bei der Arbeit Buch IV / NL: WBDA 2016 / EU: Richtlinie 2014/68/EU). Aus den Berechnungsmodellen können keine Rechtsansprüche abgeleitet werden.',
    copyrightHolder: 'Hochdrucktrailer Prüfung (Benelux)',
  },
  navItems: [
    {
      id: 'home',
      label: 'Startseite',
      slug: '/',
      shortTitle: 'Startseite',
      seoTitle: 'Hochdrucktrailer Prüfung | Gesetzgebung, DGRL & Prüfpflicht Benelux',
      seoDescription: 'Unabhängige Fachinformationen über gesetzliche Prüfpflichten, DGRL Kategorie IV, die 2-Liter-Grenze und Total Cost of Ownership bei Heißwasser- und Dampf-Hochdrucktrailern.',
    },
    {
      id: 'wbda-2016',
      label: 'Gesetzgebung Benelux',
      slug: '/regelgeving-wbda-2016',
      shortTitle: 'Gesetzgebung Benelux',
      seoTitle: 'Rechtlicher Rahmen Hochdrucktrailer: LU (ITM), BE (Codex) & NL (WBDA)',
      seoDescription: 'Gesetzliche Anforderungen an Hochdrucktrailer in Luxemburg (ITM), Belgien (Codex & EDTC) und den Niederlanden (WBDA 2016). Was Sie beim Kauf über die Prüfpflicht wissen müssen.',
    },
    {
      id: 'two-liter-grens',
      label: 'Die 2-Liter-Grenze',
      slug: '/2-liter-grens-ped',
      shortTitle: '2-Liter-Grenze',
      seoTitle: 'Die 2-Liter-Grenze bei Hochdrucktrailern: SEP vs. Kat. IV Prüfpflicht',
      seoDescription: 'Warum das Volumen des Brenners/Wärmetauschers (2 Liter) bei Hochdrucktrailern die gesetzliche Trennlinie zwischen prüffreier Ingenieurpraxis und schwerer DGRL Kategorie IV bildet.',
    },
    {
      id: 'keuringsverplichtingen',
      label: 'Prüfleitfaden',
      slug: '/keuringswijzer-verplichtingen',
      shortTitle: 'Prüfleitfaden',
      seoTitle: 'Prüfung Hochdrucktrailer: Inbetriebnahmeprüfung, Wiederholungsprüfung & Teilebindung',
      seoDescription: 'Leitfaden zur gesetzlichen Prüfung vor Inbetriebnahme, wiederkehrenden Prüfungen durch zugelassene Stellen (EDTC, ITM, NL-CBI) und dem Verbot von Universalschläuchen bei Kategorie IV.',
    },
    {
      id: 'internationaal',
      label: 'International & EU',
      slug: '/internationale-wetgeving-drukapparatuur',
      shortTitle: 'International',
      seoTitle: 'Internationale Vorschriften für Hochdrucktrailer (EU & Weltweit)',
      seoDescription: 'Wie die europäische DGRL 2014/68/EU in Luxemburg (ITM), Belgien (Codex), den Niederlanden (WBDA), Deutschland (BetrSichV) und Großbritannien (PSSR) umgesetzt wird.',
    },
    {
      id: 'tco-calculator',
      label: 'TCO-Rechner',
      slug: '/tco-keuringskosten-calculator',
      shortTitle: 'TCO-Rechner',
      seoTitle: 'TCO-Rechner Hochdrucktrailer: Prüfkosten & Stillstandszeiten Berechnen',
      seoDescription: 'Berechnen Sie die realen 10-Jahres-Betriebskosten eines Hochdrucktrailers inklusive Abnahmeprüfung, wiederkehrenden Audits, Ausfalltagen und herstellergebundenen Ersatzteilen.',
    },
    {
      id: 'downloadcenter',
      label: 'Checkliste Download',
      slug: '/download-keuringschecklist',
      shortTitle: 'Checkliste',
      seoTitle: 'Beschaffungs- und Prüfcheckliste für Hochdrucktrailer herunterladen (PDF)',
      seoDescription: 'Praktische Checkliste für Einkauf und Flottenmanagement mit 10 gezielten Kontrollfragen, die Sie vor der Unterzeichnung des Kaufvertrags stellen sollten.',
    },
    {
      id: 'faq',
      label: 'Häufige Fragen',
      slug: '/veelgestelde-vragen',
      shortTitle: 'FAQ',
      seoTitle: 'Häufige Fragen zur Prüfpflicht bei Hochdrucktrailern | Hochdrucktrailer Prüfung',
      seoDescription: 'Antworten auf zentrale rechtliche und technische Fragen zu Hochdrucktrailern, Prüfpflichten, Überwachungsstellen, Ersatzteilbindung, Strafen und Verkaufsargumenten.',
    },
  ],
  hero: {
    badge: 'Gesetzliche Vorschriften für Hochdrucktrailer: LU (ITM) • BE (Codex) • NL (WBDA) • DGRL 2014/68/EU',
    title: 'Hochdrucktrailer & Dampfeinheiten,',
    titleHighlight: 'Was Sie beim Kauf Wissen Müssen',
    description: 'Beim Kauf von professionellen Heißwasser- und Dampf-Hochdrucktrailern liegt der Fokus meist auf Arbeitsdruck und Reinigungsleistung. Was Sie jedoch auch wissen müssen: Die wiederkehrende Prüfung einer DGRL Kategorie IV Anlage ist gesetzlich vorgeschrieben. Entdecken Sie die rechtlichen Vorschriften, die 2-Liter-Grenze und die realen Betriebskosten.',
    ctaCalculator: 'TCO & Prüfkosten Berechnen',
    ctaWizard: 'Hochdrucktrailer Prüfen',
    stats: [
      {
        value: '2 Liter',
        label: 'Kippgrenze Brenner / Wärmetauscher',
        sublabel: 'Gute Ingenieurpraxis vs. Kat. IV Pflicht',
      },
      {
        value: '12–24 Mon.',
        label: 'Gesetzliche Wiederholungsprüfung',
        sublabel: 'EDTC (Vinçotte) & NL-CBI / ITM',
      },
      {
        value: '18.500 €+',
        label: 'TCO-Differenz pro Hochdrucktrailer',
        sublabel: 'Prüfungen, Stillstand & Teilebindung',
      },
    ],
  },
  wizard: {
    badge: 'Interaktiver Entscheidungsbaum für Hochdrucktrailer',
    title: 'Ist Ihr Hochdrucktrailer Prüfpflichtig oder Nicht?',
    subtitle: 'Beantworten Sie 3 kurze Fragen zu den Konstruktionsparametern Ihres Hochdrucktrailers oder mobilen Skids und erfahren Sie sofort den gesetzlichen Status in Luxemburg, Belgien und den Niederlanden.',
    openButtonText: 'Prüf-Check Jetzt Starten',
    stepIndicator: 'Schritt {step} von {total}',
    questions: {
      q1: {
        title: 'Welchen Betriebsdruck (PS) und welche Wassertemperatur (TS) hat Ihr Hochdrucktrailer?',
        description: 'Die europäische Druckgeräterichtlinie setzt strenge Schwellenwerte für Heißwasser und Dampf (> 110 °C).',
        optA_title: 'Heißwasser & Dampf (> 31,25 bar UND > 110 °C)',
        optA_desc: 'Typisch für gewerbliche Heißwasser- und Dampf-Hochdrucktrailer (Fassadenreinigung, Kaugummientfernung, Unkrautvernichtung).',
        optB_title: 'Kaltwasser oder Niederdruck (≤ 31,25 bar ODER ≤ 110 °C)',
        optB_desc: 'Kaltwasser-Hochdrucktrailer oder Reiniger, die streng unter der 110 °C Siedegrenze bleiben.',
      },
      q2: {
        title: 'Wie groß ist das tatsächliche Wasservolumen (V) des Brenners/Wärmetauschers?',
        description: 'Bei Heißwasser > 110 °C und > 31,25 bar entscheidet das Flüssigkeitsvolumen über die Risikoeinstufung gemäß DGRL Anhang II Tabelle 5.',
        optA_title: 'Streng maximal 2 Liter (V ≤ 2 L)',
        optA_desc: 'Kompakte Durchlaufspirale / Monocoil-Kessel mit einem Wasserinhalt von höchstens 2 Litern.',
        optB_title: 'Mehr als 2 Liter (V > 2 L)',
        optB_desc: 'Klassische große Heizspirale oder Kesselkörper mit mehr als 2 Litern Inhalt (oft 3 bis 15 Liter).',
      },
      q3: {
        title: 'Verfügt der Hochdrucktrailer über ein Kategorie-IV-Baugruppenzertifikat mit NoBo-Kennnummer?',
        description: 'Prüfen Sie das Typenschild des Trailers auf eine 4-stellige Kennnummer einer benannten Stelle (z. B. 0036 TÜV, 0029 Apragaz, 0620 Kiwa).',
        optA_title: 'Ja, CE mit 4-stelliger NoBo-Nummer (Kat. IV Baugruppe)',
        optA_desc: 'Der Hersteller hat die Gesamtanlage als Kategorie-IV-Baugruppe zertifizieren lassen und legt eine offizielle EU-Konformitätserklärung bei.',
        optB_title: 'Nein / Keine 4-stellige NoBo-Nummer (Nur allgemeine CE-Kennzeichnung)',
        optB_desc: 'Der Hochdrucktrailer trägt nur eine CE-Kennzeichnung nach Maschinenrichtlinie oder für den Einzelbrenner, aber KEIN DGRL Kat. IV Baugruppenzertifikat.',
      },
    },
    results: {
      green_sep: {
        title: 'Prüffreier Hochdrucktrailer unter Guter Ingenieurpraxis (SEP / Art. 4 Abs. 3)',
        subtitle: 'Keine Abnahmeprüfung und keine wiederkehrenden Prüfpflichten in Benelux',
        summary: 'Weil das Wasservolumen des Brenners/Wärmetauschers maximal 2 Liter beträgt, fällt dieser Hochdrucktrailer unter Artikel 4 Absatz 3 der europäischen Druckgeräterichtlinie 2014/68/EU (Sound Engineering Practice).',
        bullets: [
          'Vollständig befreit von der Prüfung vor Inbetriebnahme durch zugelassene Inspektionsstellen (EDTC, ITM, NL-CBI).',
          'Keine gesetzlich erzwungenen 1- oder 2-jährlichen Wiederholungsprüfungen und keine teuren Betriebsstillstände.',
          'Keine Herstellerbindung: Sie behalten die volle Freiheit, zertifizierte Universalschläuche, Lanzen und Kupplungen frei zu wählen.',
          'Standardmäßige arbeitsrechtliche Sicherheitswartung an Motor, Pumpe und Fahrgestell bleibt selbstverständlich bestehen.',
        ],
      },
      exempt: {
        title: 'Außerhalb des Kritischen Druckbereichs',
        subtitle: 'Keine Einstufung in Kategorie IV für diesen Hochdrucktrailer',
        summary: 'Das Gerät unterschreitet die Schwellenwerte von 31,25 bar oder 110 °C und fällt daher nicht unter die strengen Vorschriften für Dampfkesselbaugruppen.',
        bullets: [
          'Keine wiederkehrende Druckgeräte-Überwachungspflicht nach dem nationalen Dampfkesselrecht.',
          'Allgemeine Arbeitsschutz- und Maschinenrichtlinienvorschriften für Hochdruckgeräte sind einzuhalten.',
        ],
      },
      red_ped4: {
        title: 'Gesetzlich Prüfpflichtiger Hochdrucktrailer: DGRL Kategorie IV Baugruppe',
        subtitle: 'Strikte Überwachungspflichten in Luxemburg, Belgien und den Niederlanden',
        summary: 'Mit einem Brenner-/Wärmetauschervolumen von mehr als 2 Litern bei über 110 °C gilt dieser Hochdrucktrailer rechtlich als mobiler Dampfkessel der DGRL Kategorie IV.',
        bullets: [
          'Prüfung vor Inbetriebnahme: Vor dem ersten Einsatz muss eine zugelassene Stelle (EDTC wie Vinçotte in BE, Luxcontrol in LU, NL-CBI in NL) die Aufstellung prüfen und abnehmen.',
          'Wiederkehrende Prüfungen: Gesetzlich vorgeschriebene Nachprüfungen mit Druckprüfung der Spirale und Prüfung des Sicherheitsventils.',
          'Strikte Ersatzteilbindung: Der Austausch von Schläuchen oder Sicherheitseinrichtungen gegen markenfremde Teile lässt das Baugruppenzertifikat sofort erlöschen.',
          'Stilllegungsrisiko durch Aufsichtsbehörden (ITM, Arbeitsinspektion) und Verlust des Versicherungsschutzes bei fehlenden Prüfberichten.',
        ],
      },
      critical_violation: {
        title: 'Nicht Konforme Konfiguration: Fehlendes Baugruppenzertifikat',
        subtitle: 'Erhebliches Rechtsrisiko für den Betreiber und fehlende Konformitätserklärung',
        summary: 'Der Hochdrucktrailer überschreitet 2 Liter Wasserinhalt bei über 110 °C, besitzt jedoch kein gültiges DGRL Kategorie IV Baugruppenzertifikat einer Benannten Stelle.',
        bullets: [
          'Diese Anlage entspricht in diesem Zustand nicht den europäischen Vorschriften für DGRL Kategorie IV Baugruppen.',
          'Ohne gültige Baugruppenzertifizierung darf das Gerät nicht als Dampfanlage in Betrieb genommen werden.',
          'Im Schadensfall drohen erhebliche Haftungs- und Regressansprüche gegen den Betreiber sowie der Verlust des Versicherungsschutzes.',
          'Fordern Sie vom Hersteller umgehend die formelle DGRL Kategorie IV EU-Konformitätserklärung für die Gesamtanlage an.',
        ],
      },
    },
  },
  tco: {
    title: 'Total Cost of Ownership (TCO) Rechner für Hochdrucktrailer',
    subtitle: 'Reale Betriebskosten berechnen: Kategorie IV Hochdrucktrailer vs. Prüffrei (< 2 Liter)',
    calculatorTitle: 'Interaktives TCO-Vergleichsmodell für Hochdrucktrailer',
    description: 'Berechnen Sie die kumulierten Zusatzkosten pro Hochdrucktrailer inklusive Erstabnahme, wiederkehrenden Audits durch zugelassene Stellen, Personalausfallkosten und herstellergebundenen Ersatzteilaufschlägen.',
    defaults: {
      machineCount: 1,
      years: 10,
      kviCostPerMachine: 1250,
      periodicInspectionCost: 1150,
      downtimeDaysPerKeuring: 2,
      downtimeCostPerDay: 650,
      partsCostDifferenceAnnual: 750,
      inspectionIntervalMonths: 24,
    },
    labels: {
      machineCount: 'Anzahl Hochdrucktrailer im Fuhrpark',
      years: 'Betriebsdauer (Jahre)',
      initialInspection: 'Prüfung vor Inbetriebnahme (Inbetriebnahmeprüfung pro Trailer)',
      periodicInspection: 'Kosten der Wiederholungsprüfung (alle 12–24 Monate pro Trailer)',
      downtimeDays: 'Stillstandstage pro Prüfung (Druckprobe, Überprüfung, Transport)',
      downtimeCost: 'Personal- & Umsatzausfall pro Stillstandstag des Hochdrucktrailers',
      partsMarkup: 'Jährlicher Mehrpreis markengebundener Originalschläuche (Ersatzteilbindung)',
      totalSavingsTitle: 'Gesamtersparnis mit Prüffreiem Hochdrucktrailer (SEP < 2L)',
      totalCat4CostTitle: 'Gesamte Prüf- & Betriebskosten für Kategorie IV Hochdrucktrailer',
      totalSepCostTitle: 'Gesamte Betriebskosten für Prüffreien Hochdrucktrailer (SEP)',
    },
  },
  faq: [
    {
      id: 'faq-1',
      category: 'Gesetzgebung',
      question: 'Welche Unterschiede bestehen in der Gesetzgebung zwischen Luxemburg (ITM), Belgien (Codex) und den Niederlanden (WBDA)?',
      answer: 'Alle drei Staaten stützen sich bei der Herstellung auf die europäische Druckgeräterichtlinie (DGRL 2014/68/EU), regeln den Betrieb jedoch national. In Luxemburg gilt das Règlement grand-ducal vom 23. Dezember 1999 mit Meldepflicht bei der ITM (Inspection du Travail et des Mines) und Prüfungen durch Organismes Agréés (z. B. Luxcontrol). In Belgien gilt der Codex über das Wohlbefinden bei der Arbeit (Buch IV Titel 3) mit Prüfungen durch zugelassene Dienste (EDTC, z. B. Vinçotte, Apragaz). In den Niederlanden regelt das WBDA 2016 die Pflichten mit NL-CBI Überwachungsstellen.',
    },
    {
      id: 'faq-2',
      category: 'Technik',
      question: 'Was bedeutet die 2-Liter-Grenze nach der europäischen DGRL 2014/68/EU?',
      answer: 'Bei Heißwasser- und Dampfanlagen über 110 °C und 31,25 bar bestimmt das Wasserinhaltvolumen von 2 Litern die Risikoeinstufung. Geräte mit bis zu 2 Litern fallen unter Artikel 4 Absatz 3 (Gute Ingenieurpraxis / SEP) und sind von wiederkehrenden Druckprüfungen befreit. Geräte mit mehr als 2 Litern fallen in die strengste europäische Klasse: DGRL Kategorie IV.',
    },
    {
      id: 'faq-3',
      category: 'Prüfungen',
      question: 'Was ist eine Prüfung vor Inbetriebnahme (KVI / Inbetriebnahmeprüfung)?',
      answer: 'Die Prüfung vor Inbetriebnahme ist eine gesetzlich vorgeschriebene Abnahmeprüfung vor Ort durch eine zugelassene Überwachungsstelle (EDTC in Belgien, Luxcontrol in Luxemburg, NL-CBI in den Niederlanden), bevor eine Kategorie-IV-Anlage zum ersten Mal gewerblich genutzt werden darf.',
    },
    {
      id: 'faq-4',
      category: 'Prüfungen',
      question: 'Wie oft müssen Hochdrucktrailer der DGRL Kategorie IV wiederkehrend geprüft werden?',
      answer: 'Die Prüffristen variieren je nach Land: In den Niederlanden gilt nach WBDA 2016 eine Frist von 24 Monaten. In Belgien schreibt der Codex standardmäßig eine jährliche Überprüfung (alle 12 Monate) durch einen EDTC vor, es sei denn, es liegt eine Ausnahmegenehmigung vor. In Luxemburg und Deutschland sind ebenfalls jährliche äußere Überprüfungen sowie regelmäßige Festigkeitsprüfungen vorgeschrieben.',
    },
    {
      id: 'faq-5',
      category: 'Kosten & Teile',
      question: 'Warum darf ich an einem Kategorie-IV-Trailer keine Universalschläuche montieren?',
      answer: 'Weil ein Kategorie-IV-Hochdrucktrailer als eine zusammenhängende Baugruppe (Assembly) unter Aufsicht einer Benannten Stelle zertifiziert ist. Das Zertifikat umfasst die spezifische Heizspirale, Sicherheitsventile und zugelassenen Hochdruckschläuche. Der Einsatz universeller Schläuche gilt rechtlich als unzulässige Änderung. Dadurch erlischt das CE-Baugruppenzertifikat sofort, der Trailer wird illegal betrieben und die Betriebshaftpflicht verweigert im Schadensfall die Deckung.',
    },
    {
      id: 'faq-6',
      category: 'Durchsetzung & Strafen',
      question: 'Welche Strafen drohen bei einer Kontrolle eines ungeprüften Hochdrucktrailers?',
      answer: 'Die Aufsichtsbehörden – die luxemburgische ITM, die belgische Arbeitsinspektion (FOD WASO) und die niederländische NLA – kontrollieren aktiv Baustellen und Reinigungsbetriebe. Der Betrieb eines ungeprüften Kategorie-IV-Trailers gilt als schwerer Arbeitsschutzverstoß. Die Behörde kann den Trailer sofort stilllegen (versiegeln) und Bußgelder im fünfstelligen Eurobereich verhängen.',
    },
    {
      id: 'faq-7',
      category: 'Gesetzgebung',
      question: 'Gilt die Prüfpflicht auch, wenn der Hersteller bereits eine CE-Kennzeichnung angebracht hat?',
      answer: 'Ja, ausnahmslos. Die CE-Kennzeichnung des Herstellers bescheinigt lediglich die ordnungsgemäße Fertigung nach europäischen Produktrichtlinien (DGRL 2014/68/EU). Die Betriebsphase unterliegt den nationalen Arbeitsschutzgesetzen. Eine Hersteller-CE ersetzt NIEMALS die gesetzlich vorgeschriebene Abnahmeprüfung vor Ort vor der ersten Inbetriebnahme.',
    },
    {
      id: 'faq-8',
      category: 'Kauf & Verkauf',
      question: 'Was sollten Sie als Käufer eines Hochdrucktrailers unbedingt über die Prüfpflicht wissen?',
      answer: 'Im Verkaufsgespräch steht verständlicherweise die Leistung im Vordergrund (z. B. 350 oder 500 bar, Fördermenge). Was Sie vorab unbedingt wissen sollten: Eine Kategorie-IV-Anlage (> 2 Liter) bringt erhebliche Betriebsverpflichtungen mit sich: Pflichtprüfungen, Ausfalltage und die Verpflichtung zu teuren Original-Ersatzschläuchen. Wenn Sie diese Faktoren von vornherein einberechnen, erhalten Sie ein realistisches Bild der Gesamtbetriebskosten (TCO).',
    },
    {
      id: 'faq-9',
      category: 'Überwachungsstellen',
      question: 'Wer darf einen Kategorie-IV-Hochdrucktrailer prüfen (EDTC vs. NL-CBI vs. ITM)?',
      answer: 'In Luxemburg erfolgt dies über behördlich anerkannte Stellen (Organismes Agréés wie Luxcontrol). In Belgien sind dies zugelassene externe Überwachungsdienste (EDTC wie Vinçotte, Apragaz). In den Niederlanden dürfen nur akkreditierte NL-CBI (wie Kiwa, TÜV, Dekra) prüfen. Eine normale Kfz-TÜV-Prüfung des Anhängerfahrgestells ist für die druckführende Dampfanlage rechtlich unwirksam.',
    },
    {
      id: 'faq-10',
      category: 'Miete & Leasing',
      question: 'Gilt die Prüfpflicht auch bei der Miete oder beim Leasing eines Heißwasser-Hochdrucktrailers?',
      answer: 'Ja, ohne Ausnahme. Jeder Arbeitgeber, der Mitarbeitern Arbeitsmittel zur Verfügung stellt, haftet für deren gesetzeskonformen Sicherheitszustand. Bei Miet- oder Leasinggeräten müssen Sie vor Arbeitsbeginn prüfen, ob der gültige Inbetriebnahmenachweis und der aktuelle Prüfbericht in den Bordunterlagen des Trailers vorhanden sind.',
    },
  ],
  checklist: [
    {
      id: 'chk-1',
      phase: 'Einkauf & Angebot',
      title: 'Wasserinhalt (V) des Brenners/Wärmetauschers schriftlich anfordern',
      description: 'Fragen Sie den Lieferanten nach dem genauen Flüssigkeitsvolumen in Litern. Liegt es strikt bei höchstens 2 Litern (prüffreie Ingenieurpraxis SEP) oder darüber (> 2 Liter = strenge Kategorie IV Pflicht)?',
      requirement: 'Art. 4.3 DGRL (SEP) vs. DGRL Kategorie IV',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-2',
      phase: 'Einkauf & Angebot',
      title: 'Auslegungsdruck (PS) und Temperatur (TS) des Trailers festhalten',
      description: 'Prüfen Sie, ob Höchstdruck (z. B. 200–500 bar) und Wassertemperatur (> 110 °C Dampf/Heißwasser) die gesetzliche Dampfkesseldefinition erfüllen.',
      requirement: 'DGRL 2014/68/EU Anhang II Tabelle 5',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-3',
      phase: 'Einkauf & Angebot',
      title: 'Ersatzteilrichtlinie und Schlauchbindung verbindlich klären',
      description: 'Lassen Sie sich schriftlich bestätigen, ob der Austausch von Hochdruckschläuchen gegen zertifizierte Universalqualitätsware ohne Verlust der CE/DGRL-Baugruppenzulassung erlaubt ist.',
      requirement: 'Codex / ITM / WBDA Art. 24 (Risiko Vendor Lock-in)',
      criticality: 'Critical Check',
    },
    {
      id: 'chk-4',
      phase: 'Einkauf & Angebot',
      title: 'Kosten für Wiederholungsprüfungen und Ausfallzeiten budgetieren',
      description: 'Bei Trailern mit Kessel > 2 Liter: Planen Sie regelmäßig Prüfgebühren (ca. 1.150 € je Intervall) sowie 2 Tage Stillstand in Ihrem Flottenbudget ein.',
      requirement: 'TCO-Betriebsbudget & Prüfzyklus der Überwachungsstelle',
      criticality: 'Recommended',
    },
    {
      id: 'chk-5',
      phase: 'Auslieferung Hochdrucktrailer',
      title: 'Typenschild des Trailers prüfen (CE + 4-stellige NoBo-Nummer)',
      description: 'Bei einem Kategorie-IV-Trailer muss auf dem Typenschild der Gesamtbaugruppe die 4-stellige Nummer der Benannten Stelle stehen (z. B. 0036, 0029, 0620).',
      requirement: 'DGRL 2014/68/EU Art. 19 / Europäische Normen',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-6',
      phase: 'Auslieferung Hochdrucktrailer',
      title: 'EU-Konformitätserklärung für die Gesamtbaugruppe einfordern',
      description: 'Verlangen Sie eine offizielle EU-Konformitätserklärung, in der die Gesamtanlage als Kategorie IV freigegeben ist. Akzeptieren Sie keine Einzelzertifikate nur für Pumpe oder Kessel.',
      requirement: 'DGRL 2014/68/EU Modul G oder B+D / B+F Baugruppe',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-7',
      phase: 'Vor dem Ersten Einsatz',
      title: 'Prüfung vor Inbetriebnahme durch zugelassene Stelle durchführen',
      description: 'Bei Trailern mit Brenner > 2 Liter: Beauftragen Sie vor dem ersten Einsatz eine akkreditierte Stelle (EDTC in BE, Luxcontrol in LU, NL-CBI in NL) mit der Aufstellungs- und Druckprüfung.',
      requirement: 'Codex Buch IV / ITM-SST / WBDA 2016 Art. 21',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-8',
      phase: 'Vor dem Ersten Einsatz',
      title: 'Sicherheitsventil, Berstscheibe und Wassermangelsicherung prüfen',
      description: 'Überprüfen Sie die Plombierung des Sicherheitsventils und testen Sie die automatische Brennerabschaltung bei Wassermangel oder Überdruck nach EN 12952.',
      requirement: 'EN 12952 / Nationale Arbeitsschutzvorschriften',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-9',
      phase: 'Betrieb & Flotte',
      title: 'Maschinenakte und Prüfberichte im Hochdrucktrailer mitführen',
      description: 'Führen Sie in einer wasserdichten Hülle am Trailer die Inbetriebnahmegenehmigung und das aktuelle Prüfzeugnis für behördliche Kontrollen stets mit.',
      requirement: 'Gesetzliche Nachweispflicht bei Baustellenkontrollen',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-10',
      phase: 'Betrieb & Flotte',
      title: 'Wiederkehrende Prüffristen im Wartungsplan verankern',
      description: 'Planen Sie mindestens 60 Tage vor Ablauf der Prüffrist den Termin mit der Überwachungsstelle ein, um Betriebsverbote und Strafen zu vermeiden.',
      requirement: 'Wiederkehrende Gesetzliche Prüffristen',
      criticality: 'Mandatory',
    },
  ],
  common: {
    readMore: 'Vollständige Erläuterung lesen',
    downloadGuide: 'PDF-Leitfaden Herunterladen',
    openDecisionTree: 'Prüf-Check Öffnen',
    calculateTco: 'Zum TCO-Rechner',
    contactNote: 'Haben Sie spezifische rechtliche oder technische Fragen zu Ihrem Maschinenpark?',
    sourceReferences: 'Offizielle Quellen: Luxemburg (Règlement grand-ducal Dampfgeräte & ITM), Belgien (Codex über das Wohlbefinden bei der Arbeit Buch IV Titel 3 & RGPT), Niederlande (WBDA 2016), Europäische Richtlinie 2014/68/EU (DGRL).',
    legalNotice: 'Aus den Inhalten dieser Plattform können keine Rechtsansprüche abgeleitet werden. Wenden Sie sich im Zweifelsfall an eine anerkannte Überwachungsstelle (EDTC in BE, Luxcontrol in LU, NL-CBI in NL).',
  },
};
