import { SiteContent } from '../types';

export const beneluxContentFr: SiteContent = {
  meta: {
    id: 'benelux',
    name: 'Contrôle remorque haute pression',
    shortName: 'Contrôle remorque haute pression',
    tagline: 'Cadres légaux, obligation de contrôle DESP Catégorie IV, seuil des 2 litres et analyse du TCO pour remorques haute pression eau chaude et vapeur en Belgique, aux Pays-Bas et au Luxembourg',
    domain: 'hogedruktrailerkeuren.eu',
    baseUrl: 'https://hogedruktrailerkeuren.eu',
    language: 'fr-BE',
    currency: '€',
    legalDisclaimer: 'Cette plateforme d’information indépendante fournit des renseignements techniques et juridiques objectifs basés sur la réglementation en vigueur (BE : Codex sur le bien-être au travail Livre IV / NL : WBDA 2016 / LU : ITM / UE : Directive 2014/68/UE). Aucun droit formel ne peut être tiré des modèles de calcul présentés.',
    copyrightHolder: 'Contrôle remorque haute pression (Benelux)',
  },
  navItems: [
    {
      id: 'home',
      label: 'Accueil',
      slug: '/',
      shortTitle: 'Accueil',
      seoTitle: 'Contrôle remorque haute pression | Réglementation, DESP & Obligations Benelux',
      seoDescription: 'Informations indépendantes sur les obligations légales, le contrôle obligatoire DESP Catégorie IV, le seuil des 2 litres et le TCO des remorques haute pression eau chaude et vapeur.',
    },
    {
      id: 'wbda-2016',
      label: 'Législation Benelux',
      slug: '/regelgeving-wbda-2016',
      shortTitle: 'Législation Remorques',
      seoTitle: 'Cadre Légal Remorques Haute Pression : BE (Codex), NL (WBDA) & LU (ITM)',
      seoDescription: 'Exigences légales pour remorques haute pression en Belgique (Codex Bien-être & EDTC), aux Pays-Bas (WBDA 2016) et au Luxembourg (ITM). Ce qu’il faut savoir à l’achat sur les obligations d’inspection.',
    },
    {
      id: 'two-liter-grens',
      label: 'La Limite des 2 Litres',
      slug: '/2-liter-grens-ped',
      shortTitle: 'Limite 2 Litres',
      seoTitle: 'La Limite des 2 Litres pour Remorques Haute Pression : SEP vs. Contrôle Cat. IV',
      seoDescription: 'Pourquoi le volume du brûleur/échangeur (2 litres) dans les remorques haute pression constitue la frontière légale entre les Règles de l’Art exemptées et le lourd régime DESP Catégorie IV.',
    },
    {
      id: 'keuringsverplichtingen',
      label: 'Guide des Contrôles',
      slug: '/keuringswijzer-verplichtingen',
      shortTitle: 'Guide Contrôles',
      seoTitle: 'Inspection Remorque Haute Pression : Visite de Mise en Service & Pièces d’Origine',
      seoDescription: 'Guide sur la visite initiale de mise en service obligatoire, les contrôles périodiques par un EDTC agréé (Vinçotte) ou NL-CBI, et l’interdiction des flexibles universels pour la Catégorie IV.',
    },
    {
      id: 'internationaal',
      label: 'International & UE',
      slug: '/internationale-wetgeving-drukapparatuur',
      shortTitle: 'International',
      seoTitle: 'Réglementation Internationale pour Remorques Haute Pression (UE & Monde)',
      seoDescription: 'Comment la DESP européenne 2014/68/UE est appliquée nationalement pour les remorques haute pression en Belgique (Codex), aux Pays-Bas (WBDA), en Allemagne (BetrSichV) et au Royaume-Uni (PSSR).',
    },
    {
      id: 'tco-calculator',
      label: 'Calculateur TCO',
      slug: '/tco-keuringskosten-calculator',
      shortTitle: 'Calculateur TCO',
      seoTitle: 'Calculateur TCO Remorque Haute Pression : Coûts d’Inspection & Temps d’Arrêt',
      seoDescription: 'Calculez le coût réel d’exploitation sur 10 ans d’une remorque haute pression : mise en service, inspections périodiques, jours d’arrêt et pièces captives face à un modèle exempté.',
    },
    {
      id: 'downloadcenter',
      label: 'Télécharger Checklist',
      slug: '/download-keuringschecklist',
      shortTitle: 'Checklist',
      seoTitle: 'Télécharger la Checklist d’Achat et d’Audit pour Remorques Haute Pression (PDF)',
      seoDescription: 'Checklist pratique d’achat et d’audit comprenant 10 questions ciblées que les gestionnaires de flotte et acheteurs doivent poser avant de signer le bon de commande.',
    },
    {
      id: 'faq',
      label: 'Questions Fréquentes',
      slug: '/veelgestelde-vragen',
      shortTitle: 'FAQ',
      seoTitle: 'Questions Fréquentes sur les Obligations de Contrôle des Remorques Haute Pression',
      seoDescription: 'Réponses aux questions juridiques et techniques majeures sur les remorques haute pression, contrôles obligatoires, EDTC, obligation de pièces de marque, sanctions et arguments commerciaux.',
    },
  ],
  hero: {
    badge: 'Cadres Légaux pour Remorques Haute Pression : BE (Codex) • NL (WBDA 2016) • LU (ITM) • DESP 2014/68/UE',
    title: 'Remorques Haute Pression & Unités Vapeur,',
    titleHighlight: 'Ce Qu’il Faut Savoir à l’Achat',
    description: 'Lors de l’achat d’une remorque haute pression eau chaude ou vapeur professionnelle, l’attention se porte souvent sur la pression et la force de nettoyage, mais ce qu’il faut absolument savoir, c’est que le contrôle périodique d’une installation DESP Catégorie IV est une obligation légale stricte. Découvrez les cadres juridiques, le seuil des 2 litres et les coûts réels d’exploitation.',
    ctaCalculator: 'Calculer le TCO & Coûts d’Inspection',
    ctaWizard: 'Vérifier Votre Remorque Haute Pression',
    stats: [
      {
        value: '2 Litres',
        label: 'Seuil Critique Brûleur / Serpentin',
        sublabel: 'SEP vs. Contrôle Cat. IV Obligatoire',
      },
      {
        value: '12–24 Mois',
        label: 'Contrôle Périodique Légal',
        sublabel: 'EDTC (Belgique) & NL-CBI / ITM',
      },
      {
        value: '18 500 €+',
        label: 'Écart de TCO par Remorque',
        sublabel: 'Inspections, arrêts & pièces captives',
      },
    ],
  },
  wizard: {
    badge: 'Arbre de Décision Interactif pour Remorques Haute Pression',
    title: 'Votre Remorque Haute Pression est-elle Soumise à Contrôle Obligatoire ?',
    subtitle: 'Répondez à 3 questions courtes sur les paramètres de conception de votre remorque ou skid mobile et découvrez immédiatement son statut légal en Belgique, aux Pays-Bas et au Luxembourg.',
    openButtonText: 'Lancer le Test de Conformité',
    stepIndicator: 'Étape {step} sur {total}',
    questions: {
      q1: {
        title: 'Quels sont la pression de service (PS) et la température de l’eau (TS) de votre remorque ?',
        description: 'La Directive Européenne Équipements Sous Pression applique des seuils stricts pour l’eau surchauffée et la vapeur (> 110 °C).',
        optA_title: 'Eau Chaude & Vapeur (> 31,25 bar ET > 110 °C)',
        optA_desc: 'Typique des remorques haute pression industrielles à eau chaude et vapeur (nettoyage de façades, élimination de chewing-gums, désherbage alternatif).',
        optB_title: 'Eau Froide ou Basse Pression (≤ 31,25 bar OU ≤ 110 °C)',
        optB_desc: 'Remorques haute pression à eau froide ou appareils restant strictement sous le seuil d’ébullition de 110 °C.',
      },
      q2: {
        title: 'Quel est le volume d’eau réel (V) du brûleur / échangeur dans la remorque ?',
        description: 'Pour l’eau surchauffée > 110 °C et > 31,25 bar, le volume interne détermine la classe de risque selon l’Annexe II Tableau 5 de la DESP.',
        optA_title: 'Strictement 2 litres maximum (V ≤ 2 L)',
        optA_desc: 'Serpentin continu compact / chaudière monocoil avec une contenance en eau égale ou inférieure à 2 litres.',
        optB_title: 'Plus de 2 litres (V > 2 L)',
        optB_desc: 'Serpentin traditionnel volumineux ou réservoir d’échangeur supérieur à 2 litres (fréquemment 3 à 15 litres).',
      },
      q3: {
        title: 'La remorque dispose-t-elle d’un certificat d’ensemble Catégorie IV avec numéro NoBo ?',
        description: 'Vérifiez sur la plaque signalétique la présence d’un numéro d’identification à 4 chiffres d’un Organisme Notifié (ex. 0029 Apragaz, 0036 TÜV, 0620 Kiwa).',
        optA_title: 'Oui, CE avec numéro NoBo à 4 chiffres (Ensemble Cat. IV)',
        optA_desc: 'Le fabricant a certifié la remorque complète en tant qu’ensemble Catégorie IV et fournit une déclaration UE officielle.',
        optB_title: 'Non / Aucun numéro NoBo à 4 chiffres (Simple CE général)',
        optB_desc: 'La remorque ne porte qu’un marquage CE standard pour la Directive Machines ou pour le brûleur isolé, mais AUCUN certificat d’ensemble DESP Cat. IV.',
      },
    },
    results: {
      green_sep: {
        title: 'Remorque Exemptée de Contrôle sous les Règles de l’Art (SEP / Art. 4 § 3)',
        subtitle: 'Aucune visite de mise en service ni contrôle périodique obligatoire en Belgique et aux Pays-Bas',
        summary: 'Le volume d’eau du brûleur/échangeur étant de 2 litres maximum, cette remorque relève de l’Article 4 paragraphe 3 de la Directive Européenne Équipements Sous Pression 2014/68/UE (Sound Engineering Practice).',
        bullets: [
          'Exempte de visite initiale de mise en service par un EDTC en Belgique (Codex Livre IV) ou un NL-CBI aux Pays-Bas.',
          'Exempte de contrôles périodiques annuels ou bisannuels obligatoires et d’arrêts d’exploitation coûteux.',
          'Aucune captivité de marque : vous conservez la liberté d’utiliser les flexibles haute pression, lances et raccords universels certifiés de votre choix.',
          'L’entretien de sécurité standard du moteur, de la pompe et du châssis reste évidemment d’application.',
        ],
      },
      exempt: {
        title: 'En Dehors du Domaine Sous Pression Critique',
        subtitle: 'Pas d’obligation de contrôle Catégorie IV pour cette remorque haute pression',
        summary: 'L’appareil reste sous les seuils de 31,25 bar ou 110 °C et échappe ainsi à la classification européenne la plus stricte relative aux générateurs de vapeur.',
        bullets: [
          'Aucune obligation d’inspection sous pression périodique contraignante selon le Codex belge ou le WBDA.',
          'Les règles de sécurité générales pour équipements de travail et la Directive Machines s’appliquent.',
        ],
      },
      red_ped4: {
        title: 'Remorque Soumise à Contrôle Légal : Ensemble DESP Catégorie IV',
        subtitle: 'Obligations d’inspection strictes en Belgique (Codex) et aux Pays-Bas (WBDA)',
        summary: 'Avec un volume d’eau du brûleur > 2 litres et une température > 110 °C, cette remorque est juridiquement qualifiée de chaudière à vapeur mobile en DESP Catégorie IV.',
        bullets: [
          'Belgique : Examen obligatoire de mise en service par un EDTC agréé (Vinçotte, Apragaz) avant la toute première utilisation (Codex Livre IV Titre 3).',
          'Pays-Bas : Visite de mise en service (KvI) obligatoire par un NL-CBI avant mise en service opérationnelle.',
          'Contrôles périodiques récurrents obligatoires avec épreuve hydrostatique du serpentin et tarage de la soupape de sûreté.',
          'Obligation stricte de pièces d’origine : remplacer des flexibles ou sécurités par des pièces non spécifiées annule immédiatement la certification de l’ensemble.',
          'Risque de mise sous scellés par l’inspection du travail et refus de prise en charge par les assurances en cas de sinistre sans rapport valide.',
        ],
      },
      critical_violation: {
        title: 'Configuration Non Conforme : Certification d’Ensemble Manquante',
        subtitle: 'Risque juridique majeur pour l’exploitant et absence de déclaration de conformité',
        summary: 'La remorque possède une contenance > 2 litres à > 110 °C, mais ne dispose pas de la certification d’ensemble requise en DESP Catégorie IV sous surveillance d’un Organisme Notifié.',
        bullets: [
          'Dans cet état, cette installation ne satisfait pas aux exigences européennes pour les ensembles DESP Catégorie IV.',
          'Sans certification d’ensemble valide, l’appareil ne peut légalement être exploité comme générateur de vapeur.',
          'En cas d’incident ou d’accident de travail, l’absence de certificat engage directement la responsabilité pénale de l’employeur.',
          'Exigez immédiatement auprès de votre fournisseur la Déclaration UE de Conformité officielle DESP Catégorie IV pour l’ensemble complet.',
        ],
      },
    },
  },
  tco: {
    title: 'Calculateur du Coût Total de Possession (TCO) pour Remorques Haute Pression',
    subtitle: 'Calculez les coûts réels d’exploitation : Remorque Catégorie IV vs Modèle Exempté (< 2 Litres)',
    calculatorTitle: 'Modèle Comparatif Interactif du TCO des Remorques Haute Pression',
    description: 'Calculez l’écart cumulé de coût par remorque haute pression en intégrant l’inspection initiale, les réexamens périodiques par EDTC / NL-CBI, la perte d’exploitation par arrêt de chantier et le surcoût des pièces d’origine captives.',
    defaults: {
      machineCount: 1,
      years: 10,
      kviCostPerMachine: 1250,
      periodicInspectionCost: 1150,
      downtimeDaysPerKeuring: 2,
      downtimeCostPerDay: 650,
      partsCostDifferenceAnnual: 750,
      inspectionIntervalMonths: 24,
    },
    labels: {
      machineCount: 'Nombre de remorques haute pression dans la flotte',
      years: 'Durée d’exploitation (années)',
      initialInspection: 'Visite de mise en service (EDTC / KvI par remorque haute pression)',
      periodicInspection: 'Coût du contrôle périodique (tous les 12 à 24 mois par EDTC / NL-CBI)',
      downtimeDays: 'Jours d’immobilisation par inspection (épreuve sous pression, examen, transport)',
      downtimeCost: 'Perte de chiffre d’affaires et coût d’équipe par jour d’immobilisation',
      partsMarkup: 'Surcoût annuel des flexibles et lances de marque imposés (captivité constructeur)',
      totalSavingsTitle: 'Économie totale avec une Remorque Haute Pression Exemptée (SEP < 2L)',
      totalCat4CostTitle: 'Coûts totaux de contrôle & d’exploitation d’une Remorque Catégorie IV',
      totalSepCostTitle: 'Coûts totaux d’exploitation d’une Remorque Exemptée (SEP)',
    },
  },
  faq: [
    {
      id: 'faq-1',
      category: 'Réglementation',
      question: 'Quelles sont les différences de législation entre la Belgique (Codex), les Pays-Bas (WBDA) et le Luxembourg (ITM) ?',
      answer: 'Les trois pays s’appuient sur la Directive Européenne Équipements Sous Pression (DESP 2014/68/UE) pour la fabrication, mais régissent la phase d’exploitation de façon nationale. En Belgique, le Codex sur le bien-être au travail (Livre IV Titre 3) et le RGPT imposent des contrôles par des EDTC agréés (tels que Vinçotte, Apragaz). Aux Pays-Bas, le WBDA 2016 délègue la surveillance aux NL-CBI (Dekra, Kiwa, TÜV). Au Luxembourg, le Règlement grand-ducal du 23 décembre 1999 impose une déclaration à l’ITM (Inspection du Travail et des Mines) et des contrôles par des Organismes Agréés (comme Luxcontrol).',
    },
    {
      id: 'faq-2',
      category: 'Technique',
      question: 'Que signifie la limite des 2 litres selon la Directive Européenne DESP 2014/68/UE ?',
      answer: 'Pour les appareils à eau surchauffée et à vapeur dépassant 110 °C et 31,25 bar, la contenance en eau de 2 litres constitue le pivot de la classification des risques. Les équipements contenant jusqu’à 2 litres relèvent de l’Article 4 paragraphe 3 (Règles de l’Art / SEP) et sont totalement exemptés de contrôles périodiques. Les équipements dépassant 2 litres basculent dans la catégorie européenne la plus sévère : la DESP Catégorie IV.',
    },
    {
      id: 'faq-3',
      category: 'Contrôles',
      question: 'Qu’est-ce qu’une visite de mise en service (KvI / examen de mise en service EDTC) ?',
      answer: 'Une visite de mise en service (Belgique : Codex Livre IV ; Pays-Bas : art. 21 WBDA 2016) est une inspection obligatoire effectuée sur site par un organisme d’inspection accrédité (EDTC ou NL-CBI) avant qu’une installation de Catégorie IV ne soit mise en service opérationnelle pour la première fois.',
    },
    {
      id: 'faq-4',
      category: 'Contrôles',
      question: 'À quelle fréquence les remorques haute pression en Catégorie IV doivent-elles être réinspectées ?',
      answer: 'L’intervalle de réinspection varie selon les pays : aux Pays-Bas, le WBDA 2016 impose un contrôle tous les 24 mois par un NL-CBI. En Belgique, le Codex sur le bien-être au travail (Livre IV Titre 3) impose par défaut une vérification annuelle (tous les 12 mois) par un EDTC agréé (ex. Vinçotte ou Apragaz), sauf dérogation formelle accordée par l’autorité compétente. Au Luxembourg et en Allemagne, des vérifications externes annuelles sont également exigées.',
    },
    {
      id: 'faq-5',
      category: 'Coûts & Pièces',
      question: 'Pourquoi ne puis-je pas monter de flexibles universels sur une remorque Catégorie IV ?',
      answer: 'Parce qu’une remorque haute pression Catégorie IV est certifiée en tant qu’ensemble unique et indissociable sous la surveillance d’un Organisme Notifié. La certification couvre le serpentin spécifique, les organes de sécurité et les flexibles d’origine. Remplacer un flexible usé par un flexible universel est juridiquement considéré comme une modification non autorisée (Article 24 WBDA / dispositions équivalentes du Codex). La certification CE d’ensemble devient caduque, la remorque fonctionne illégalement et l’assureur peut décliner toute prise en charge en cas d’accident.',
    },
    {
      id: 'faq-6',
      category: 'Contrôle & Sanctions',
      question: 'Quelles sanctions l’Inspection du Travail applique-t-elle en cas de remorque non contrôlée ?',
      answer: 'Les autorités de contrôle – le SPF Emploi (CBE) en Belgique, la NLA aux Pays-Bas et l’ITM au Luxembourg – inspectent activement les chantiers de nettoyage de façade, de voirie et industriels. Exploiter une remorque Catégorie IV sans attestation de contrôle valide constitue une infraction pénale grave à la sécurité du travail. L’inspecteur peut ordonner l’arrêt immédiat des travaux (mise sous scellés) et infliger des amendes administratives et pénales pouvant atteindre plusieurs dizaines de milliers d’euros.',
    },
    {
      id: 'faq-7',
      category: 'Réglementation',
      question: 'L’obligation de contrôle s’applique-t-elle même si le constructeur a apposé le marquage CE ?',
      answer: 'Oui, sans aucune exception. Le marquage CE du constructeur prouve uniquement que la remorque et son serpentin ont été fabriqués conformément aux normes de production européennes (DESP 2014/68/UE). La phase d’exploitation relève des lois nationales de sécurité au travail (Codex en Belgique, WBDA aux Pays-Bas). Le marquage CE ne remplace JAMAIS la visite obligatoire de mise en service sur site par un organisme agréé.',
    },
    {
      id: 'faq-8',
      category: 'Achat & Vente',
      question: 'Que devez-vous absolument savoir en tant qu’acheteur concernant les obligations d’inspection ?',
      answer: 'Lors du processus d’achat, le discours commercial se concentre naturellement sur les performances (ex. 350 ou 500 bar), le débit et la température. Ce qu’il faut également savoir avant de signer, c’est qu’une remorque Catégorie IV (> 2 litres) entraîne des contraintes d’exploitation lourdes : visite de mise en service obligatoire, contrôles périodiques récurrents, arrêts de production et obligation de racheter des flexibles d’origine de marque. Intégrer ces aspects dès l’achat permet de chiffrer précisément le coût global de possession (TCO).',
    },
    {
      id: 'faq-9',
      category: 'Inspections',
      question: 'Qui est habilité à inspecter une remorque Catégorie IV (EDTC vs NL-CBI) ?',
      answer: 'En Belgique, ces contrôles sont strictement réservés aux Services Externes pour les Contrôles Techniques agréés (EDTC, comme Vinçotte, BTV, Apragaz). Aux Pays-Bas, seuls les NL-CBI agréés (Kiwa, TÜV, Dekra, DNV) sont habilités. Un contrôle technique automobile ordinaire de la remorque routière ou un contrôle électrique générique n’a AUCUNE valeur légale pour l’installation sous pression.',
    },
    {
      id: 'faq-10',
      category: 'Location & Leasing',
      question: 'L’obligation de contrôle s’applique-t-elle aussi en cas de location ou de leasing d’une remorque ?',
      answer: 'Oui, expressément. En vertu du droit du bien-être au travail, l’employeur qui met un équipement de travail à disposition de ses salariés est civilement et pénalement responsable de la conformité de cet équipement. En cas de location ou de leasing, vous devez obligatoirement exiger et vérifier la présence de l’attestation de mise en service et du dernier rapport d’inspection en cours de validité dans les documents de bord de la remorque.',
    },
  ],
  checklist: [
    {
      id: 'chk-1',
      phase: 'Achat & Devis',
      title: 'Demander par écrit le volume d’eau (V) du brûleur / échangeur',
      description: 'Demandez au fournisseur la contenance exacte en litres du serpentin thermique. Est-il strictement inférieur ou égal à 2 litres (exempté SEP) ou supérieur (> 2 litres = contrôle Catégorie IV obligatoire) ?',
      requirement: 'Art. 4.3 DESP (SEP) vs. DESP Catégorie IV',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-2',
      phase: 'Achat & Devis',
      title: 'Vérifier la pression de calcul (PS) et la température maximale (TS)',
      description: 'Vérifiez si la pression maximale (ex. 200–500 bar) et la température (> 110 °C vapeur / eau surchauffée) déclenchent la définition légale d’un générateur de vapeur.',
      requirement: 'DESP 2014/68/UE Annexe II Tableau 5',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-3',
      phase: 'Achat & Devis',
      title: 'Clarifier la politique de pièces de rechange et la captivité des flexibles',
      description: 'Demandez par écrit si l’utilisation de flexibles haute pression universels certifiés est autorisée sans invalider la certification CE/DESP de l’ensemble.',
      requirement: 'Codex Livre IV / WBDA Art. 24 (Risque Vendor Lock-in)',
      criticality: 'Critical Check',
    },
    {
      id: 'chk-4',
      phase: 'Achat & Devis',
      title: 'Budgétiser les contrôles périodiques et les jours d’immobilisation',
      description: 'Si vous optez pour une remorque avec brûleur > 2 litres : intégrez d’emblée les coûts de contrôle récurrents (env. 1 150 € par session) et 2 jours d’arrêt machine dans votre budget prévisionnel.',
      requirement: 'Budget d’Exploitation TCO & Cycle EDTC / NL-CBI',
      criticality: 'Recommended',
    },
    {
      id: 'chk-5',
      phase: 'Livraison de la Remorque',
      title: 'Contrôler la plaque signalétique (CE + numéro NoBo à 4 chiffres)',
      description: 'Pour une remorque Catégorie IV, la plaque de l’ensemble complet doit comporter le numéro à 4 chiffres de l’Organisme Notifié (ex. 0029, 0036, 0620).',
      requirement: 'DESP 2014/68/UE Art. 19 / Normes Européennes',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-6',
      phase: 'Livraison de la Remorque',
      title: 'Exiger la Déclaration UE de Conformité pour l’Ensemble Complet',
      description: 'Exigez une déclaration officielle dans laquelle l’ensemble de la remorque est homologué en Catégorie IV, et refusez la livraison si seules des attestations séparées pour la pompe ou la chaudière sont fournies.',
      requirement: 'DESP 2014/68/UE Module G ou B+D / B+F Ensemble',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-7',
      phase: 'Avant Premier Chantier',
      title: 'Faire réaliser la visite de mise en service par un EDTC ou NL-CBI',
      description: 'Pour les remorques avec brûleur > 2 litres : mandatez un EDTC agréé (Belgique) ou NL-CBI (Pays-Bas) pour l’inspection réglementaire avant le premier chantier.',
      requirement: 'Codex Livre IV Titre 3 / WBDA 2016 Art. 21',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-8',
      phase: 'Avant Premier Chantier',
      title: 'Vérifier la soupape de sûreté et les sécurités de manque d’eau',
      description: 'Vérifiez le plombage de la soupape de sûreté à ressort et testez la coupure automatique du brûleur en cas de manque d’eau ou de surpression selon la norme EN 12952.',
      requirement: 'EN 12952 / Prescriptions de Sécurité Codex & WBDA',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-9',
      phase: 'Gestion & Flotte',
      title: 'Conserver le dossier machine et les rapports d’inspection à bord',
      description: 'Conservez dans une pochette étanche à bord de la remorque l’attestation de mise en service et le dernier rapport d’inspection pour tout contrôle de l’Inspection du Travail.',
      requirement: 'Obligation Légale de Preuve & Contrôle des Chantiers',
      criticality: 'Mandatory',
    },
    {
      id: 'chk-10',
      phase: 'Gestion & Flotte',
      title: 'Planifier les réinspections périodiques dans le planning de maintenance',
      description: 'Programmez au moins 60 jours avant l’échéance légale l’intervention d’un organisme agréé pour éviter tout risque d’exploitation illégale et d’amendes.',
      requirement: 'Contrôles Périodiques Obligatoires Codex / WBDA',
      criticality: 'Mandatory',
    },
  ],
  common: {
    readMore: 'Lire l’explication complète',
    downloadGuide: 'Télécharger le Guide PDF',
    openDecisionTree: 'Ouvrir le Test de Conformité',
    calculateTco: 'Accéder au Calculateur TCO',
    contactNote: 'Vous avez des questions juridiques ou techniques précises sur votre parc de machines ?',
    sourceReferences: 'Sources officielles : Belgique (Codex sur le bien-être au travail Livre IV Titre 3 & RGPT art. 269–283ter), Pays-Bas (WBDA 2016), Luxembourg (Règlement grand-ducal générateurs de vapeur & ITM), Directive Européenne 2014/68/UE (DESP).',
    legalNotice: 'Aucun droit juridique formel ne peut être tiré des contenus de cette plateforme. En cas de doute, consultez un organisme d’inspection agréé (EDTC en Belgique, NL-CBI aux Pays-Bas, Organisme agréé au Luxembourg).',
  },
};
