import { SiteContent } from '../types';

export const beneluxContent: SiteContent = {
  meta: {
    id: 'benelux',
    name: 'Hogedruktrailer keuren',
    shortName: 'Hogedruktrailer keuren',
    tagline: 'Wettelijke kaders, PED Categorie IV keuringsplicht, 2-liter grens en TCO-analyse voor heetwater- en stoom-hogedruktrailers in Nederland, België en Luxemburg',
    domain: 'hogedruktrailerkeuren.nl',
    baseUrl: 'https://hogedruktrailerkeuren.nl',
    language: 'nl-NL',
    currency: '€',
    legalDisclaimer: 'Dit onafhankelijke kennisplatform verstrekt objectieve technische en juridische voorlichting op basis van vigerende wet- en regelgeving (NL: WBDA 2016 & Arbowet / BE: Codex Welzijn op het Werk Boek IV / LU: ITM / EU: Richtlijn 2014/68/EU). Aan de getoonde rekenmodellen kunnen geen formele rechten worden ontleend.',
    copyrightHolder: 'Hogedruktrailer keuren (Benelux)',
  },
  navItems: [
    {
      id: 'home',
      label: 'Home',
      slug: '/',
      shortTitle: 'Home',
      seoTitle: 'Hogedruktrailer keuren | Wetgeving, PED & Keuringsplicht Benelux',
      seoDescription: 'Onafhankelijke informatie over wettelijke verplichtingen, PED Categorie IV keuringsplicht, 2-liter grens en Total Cost of Ownership bij heetwater- en stoom-hogedruktrailers.',
    },
    {
      id: 'wbda-2016',
      label: 'Wetgeving Benelux',
      slug: '/regelgeving-wbda-2016',
      shortTitle: 'Wetgeving Hogedruktrailers',
      seoTitle: 'Wettelijk Kader Hogedruktrailers: NL (WBDA), BE (Codex) & LU (ITM) | Hogedruktrailer keuren',
      seoDescription: 'Wettelijke eisen voor hogedruktrailers in Nederland (WBDA 2016 / NL-CBI), België (Codex Welzijn & EDTC) en Luxemburg (ITM). Wat u eigenlijk ook moet weten bij de aankoop over de keuringsplicht.',
    },
    {
      id: 'two-liter-grens',
      label: 'De 2-Liter Grens',
      slug: '/2-liter-grens-ped',
      shortTitle: '2-Liter Grens',
      seoTitle: 'De 2-Liter Grens bij Hogedruktrailers: SEP vs. Cat. IV Keuring | Hogedruktrailer keuren',
      seoDescription: 'Waarom de inhoud van de brander/warmtewisselaar (2 liter) in hogedruktrailers de wettelijke scheidslijn vormt tussen keuringsvrij Goed Vakmanschap en zware PED Categorie IV keuringsplicht.',
    },
    {
      id: 'keuringsverplichtingen',
      label: 'Keuringswijzer',
      slug: '/keuringswijzer-verplichtingen',
      shortTitle: 'Keuringswijzer',
      seoTitle: 'Keuring Hogedruktrailer: KvI, 2-Jaarlijkse Herkeuring & Merkplicht | Hogedruktrailer keuren',
      seoDescription: 'Gids over de verplichte Keuring voor Ingebruikneming (KvI), tweejaarlijkse herkeuring door NL-CBI of Belgische EDTC, en het verbod op universele slangen bij Categorie IV hogedruktrailers.',
    },
    {
      id: 'internationaal',
      label: 'Internationaal & EU',
      slug: '/internationale-wetgeving-drukapparatuur',
      shortTitle: 'Internationaal',
      seoTitle: 'Internationale Regelgeving voor Hogedruktrailers (EU & Wereldwijd) | Hogedruktrailer keuren',
      seoDescription: 'Hoe de Europese PED 2014/68/EU landspecifiek wordt gehandhaafd voor hogedruktrailers in Nederland (WBDA), België (Codex), Duitsland (BetrSichV) en het Verenigd Koninkrijk (PSSR).',
    },
    {
      id: 'tco-calculator',
      label: 'TCO Calculator',
      slug: '/tco-keuringskosten-calculator',
      shortTitle: 'TCO Calculator',
      seoTitle: 'TCO Calculator Hogedruktrailer: Bereken Inspectiekosten & Stilstand | Hogedruktrailer keuren',
      seoDescription: 'Bereken de werkelijke 10-jaars exploitatiekosten van een hogedruktrailer inclusief KvI, periodieke herkeuringen, stilstandsdagen en merkgebonden onderdelen t.o.v. een keuringsvrije hogedruktrailer.',
    },
    {
      id: 'downloadcenter',
      label: 'Download Checklist',
      slug: '/download-keuringschecklist',
      shortTitle: 'Checklist',
      seoTitle: 'Download Inkoop- en Keuringschecklist voor Hogedruktrailers (PDF) | Hogedruktrailer keuren',
      seoDescription: 'Praktische inkoop- en auditchecklist met 10 gerichte controlevragen die wagenparkbeheerders en inkopers vooraf kunnen meenemen bij de aankoop.',
    },
    {
      id: 'faq',
      label: 'Veelgestelde Vragen',
      slug: '/veelgestelde-vragen',
      shortTitle: 'FAQ',
      seoTitle: 'Veelgestelde Vragen over Keuringsplicht bij Hogedruktrailers | Hogedruktrailer keuren',
      seoDescription: 'Antwoorden op de meest gestelde juridische en technische vragen over hogedruktrailers, keuringsplichten, NL-CBI’s, merkplicht, sancties en verkoopargumenten.',
    },
  ],
  hero: {
    badge: 'Wettelijke Kaders voor Hogedruktrailers: NL (WBDA 2016) • BE (Codex Welzijn) • PED 2014/68/EU',
    title: 'Hogedruktrailers & Stoomunits,',
    titleHighlight: 'Wat u Moet Weten bij Aankoop',
    description: 'Bij de aankoop van professionele heetwater- en stoom-hogedruktrailers ligt de focus vaak op werkdruk en reinigingskracht, maar wat u eigenlijk ook moet weten is dat periodieke herkeuring van een PED Categorie IV installatie wettelijk verplicht is. Ontdek de juridische kaders, de 2-liter grens en de werkelijke exploitatiekosten.',
    ctaCalculator: 'Bereken Hogedruktrailer TCO & Keuringskosten',
    ctaWizard: 'Check Uw Hogedruktrailer',
    stats: [
      {
        value: '2 Liter',
        label: 'Kantelgrens Brander/Warmtewisselaar',
        sublabel: 'SEP vs. Cat. IV Keuringsplicht',
      },
      {
        value: '24 Mnd',
        label: 'Wettelijke Herkeuring',
        sublabel: 'NL-CBI & Belgische EDTC',
      },
      {
        value: '€ 18.500+',
        label: 'TCO Verschil per Hogedruktrailer',
        sublabel: 'Inspecties, stilstand & merkplicht',
      },
    ],
  },
  wizard: {
    badge: 'Interactieve Beslisboom Hogedruktrailers',
    title: 'Keuringsplichtige Hogedruktrailer of Niet?',
    subtitle: 'Beantwoord 3 korte vragen over de ontwerpparameters van uw hogedruktrailer of mobiele skid en ontdek direct de wettelijke status in Nederland en België.',
    openButtonText: 'Start Direct de Keurings-Check',
    stepIndicator: 'Stap {step} van {total}',
    questions: {
      q1: {
        title: 'Wat zijn de werkdruk (PS) en watertemperatuur (TS) van uw hogedruktrailer?',
        description: 'De Europese Richtlijn Drukapparatuur hanteert specifieke ondergrenzen voor oververhit water en stoom (> 110 °C).',
        optA_title: 'Heetwater & Stoom (> 31,25 bar én > 110 °C)',
        optA_desc: 'Typisch voor industriële heetwater- en stoom-hogedruktrailers (gevelreiniging, kauwgomverwijdering, onkruidbestrijding).',
        optB_title: 'Koudwater of Lagedruk (≤ 31,25 bar of ≤ 110 °C)',
        optB_desc: 'Koudwater-hogedruktrailers of reinigers die strikt onder de kookgrens van 110 °C blijven.',
      },
      q2: {
        title: 'Wat is de fysieke waterinhoud (V) van de brander/warmtewisselaar in de hogedruktrailer?',
        description: 'Bij oververhit water > 110 °C en > 31,25 bar bepaalt het interne vloeistofvolume de risicoclassificatie conform PED Bijlage II Tabel 5.',
        optA_title: 'Strikt maximaal 2 liter (V ≤ 2 L)',
        optA_desc: 'Compacte doorstroomspiraal / monocoil ketel met een waterinhoud van 2 liter of minder.',
        optB_title: 'Meer dan 2 liter (V > 2 L)',
        optB_desc: 'Klassieke grote verwarmingsspiraal of brander/warmtewisselaarsvat met een inhoud groter dan 2 liter (vaak 3 tot 15 liter).',
      },
      q3: {
        title: 'Beschikt de hogedruktrailer over een Categorie IV Samenstelcertificaat met NoBo-nummer?',
        description: 'Controleer het typeplaatje van de hogedruktrailer op een viercijferig identificatienummer van een Notified Body (zoals 0036 TÜV, 0029 Apragaz of 0620 Kiwa).',
        optA_title: 'Ja, CE met 4-cijferig NoBo-nummer (Cat. IV Samenstel)',
        optA_desc: 'De fabrikant heeft de complete hogedruktrailer als Categorie IV samenstel laten certificeren en levert een officiële EU-verklaring mee.',
        optB_title: 'Nee / Geen 4-cijferig NoBo-nummer (Louter algemene CE)',
        optB_desc: 'De hogedruktrailer heeft enkel een algemene CE-markering voor de Machinerichtlijn of de losse brander/warmtewisselaar, maar GEEN PED Cat. IV samenstelcertificaat.',
      },
    },
    results: {
      green_sep: {
        title: 'Keuringsvrije Hogedruktrailer onder Goed Vakmanschap (SEP / Art. 4 lid 3)',
        subtitle: 'Geen KvI-plicht en geen periodieke keuringen in Nederland en België',
        summary: 'Omdat het watervolume van de brander/warmtewisselaar maximaal 2 liter is, valt deze hogedruktrailer onder Artikel 4 lid 3 van de Europese Richtlijn Drukapparatuur 2014/68/EU (Sound Engineering Practice).',
        bullets: [
          'Vrijgesteld van Keuring voor Ingebruikneming (KvI) door een NL-CBI in Nederland.',
          'Vrijgesteld van verplichte indienststellingskeuring door een EDTC in België.',
          'Geen verplichte tweejaarlijkse herkeuringen of kostbare stilstand van de hogedruktrailer.',
          'Geen merkgebondenheid: u behoudt de vrijheid om gecertificeerde universele hogedrukslangen, lansen en koppelingen naar keuze in te zetten.',
          'Standaard arbotechnisch periodiek onderhoud aan motor, pomp en chassis blijft uiteraard van kracht.',
        ],
      },
      exempt: {
        title: 'Buiten het Zware Drukbereik',
        subtitle: 'Geen Categorie IV keuringsplicht voor deze hogedruktrailer',
        summary: 'De machine blijft onder de drempelwaarde van 31,25 bar of 110 °C en valt daarmee buiten de zwaarste Europese stoomketelclassificatie.',
        bullets: [
          'Geen zware periodieke keuringsplicht onder WBDA 2016 of Belgische Codex.',
          'Standaard Arbo- en Machinerichtlijn onderhoudsvoorschriften voor hogedrukapparatuur zijn van toepassing.',
        ],
      },
      red_ped4: {
        title: 'Wettelijk Keuringsplichtige Hogedruktrailer: PED Categorie IV Samenstel',
        subtitle: 'Strikte inspectieverplichtingen in Nederland (WBDA) en België (Codex)',
        summary: 'Met een inhoud van de brander/warmtewisselaar > 2 liter en stoom-/watertemperatuur > 110 °C geldt deze hogedruktrailer juridisch als een mobiele stoomketel in PED Categorie IV.',
        bullets: [
          'Nederland: Verplichte Keuring voor Ingebruikneming (KvI) door een NL-CBI vóórdat de hogedruktrailer de eerste werkdag ingezet wordt (Art. 21 WBDA).',
          'België: Verplicht indienststellingsonderzoek door een erkende EDTC (Codex Boek IV Titel 3).',
          'Verplichte tweejaarlijkse periodieke herkeuring met afpersen van de spiraal en beproeving van de veiligheidsklep.',
          'Strikte merkplicht: vervanging van slangen of veiligheden door niet-gespecificeerde delen laat het samenstelcertificaat direct vervallen.',
          'Risico op stillegging door toezichthouders en discussie over verzekeringsdekking bij ontbreken van het actuele keuringsrapport.',
        ],
      },
      critical_violation: {
        title: 'Niet-Conforme Configuratie: Ontbrekende Samenstelkeuring',
        subtitle: 'Wettelijk risico voor de eigenaar en ontbrekende conformiteitsverklaring',
        summary: 'De hogedruktrailer heeft een inhoud > 2 liter bij > 110 °C, maar beschikt niet over de vereiste PED Categorie IV samenstelcertificering met Notified Body toezicht.',
        bullets: [
          'Deze installatie voldoet in deze staat niet aan de Europese voorschriften voor PED Categorie IV samenstellen.',
          'Zonder geldige samenstelcertificering mag de installatie niet als stoominstallatie in bedrijf worden genomen.',
          'Bij een eventuele calamiteit kan het ontbreken van een geldig certificaat leiden tot discussie over aansprakelijkheid en verzekeringsdekking.',
          'Vraag bij de leverancier naar de formele PED Categorie IV EU-conformiteitsverklaring van het totale samenstel.',
        ],
      },
    },
  },
  tco: {
    title: 'Total Cost of Ownership (TCO) Calculator Hogedruktrailers',
    subtitle: 'Bereken de werkelijke exploitatiekosten: Categorie IV Hogedruktrailer vs. Keuringsvrij (< 2 Liter)',
    calculatorTitle: 'Interactief TCO Vergelijkingsmodel Hogedruktrailers',
    description: 'Bereken het cumulatieve kostenverschil per hogedruktrailer inclusief initiële KvI, tweejaarlijkse NL-CBI / EDTC herkeuringen, personele stilstandsderving en merkgebonden onderdelenopslag.',
    defaults: {
      machineCount: 1,
      years: 10,
      kviCostPerMachine: 1250,
      periodicInspectionCost: 1150,
      downtimeDaysPerKeuring: 2,
      downtimeCostPerDay: 650,
      partsCostDifferenceAnnual: 750,
      inspectionIntervalMonths: 24,
    },
    labels: {
      machineCount: 'Aantal hogedruktrailers in het wagenpark',
      years: 'Exploitatieperiode (jaren)',
      initialInspection: 'Keuring voor Ingebruikneming (KvI / Indienststelling per hogedruktrailer)',
      periodicInspection: 'Kosten herkeuring (elke 24 maanden door NL-CBI / EDTC per hogedruktrailer)',
      downtimeDays: 'Dagen stilstand per herkeuring (afpersen, inspectie, transport)',
      downtimeCost: 'Personele & omzetderving per dag stilstand van de hogedruktrailer',
      partsMarkup: 'Jaarlijkse meerprijs merkgebonden originele slangen en appendages (merkplicht)',
      totalSavingsTitle: 'Totale besparing met Keuringsvrije Hogedruktrailer (SEP < 2L)',
      totalCat4CostTitle: 'Totale keurings- & exploitatiekosten Categorie IV Hogedruktrailer',
      totalSepCostTitle: 'Totale exploitatiekosten Keuringsvrije Hogedruktrailer (SEP)',
    },
  },
  faq: [
    {
      id: 'faq-1',
      category: 'Regelgeving',
      question: 'Wat zijn de verschillen in wetgeving tussen Nederland (WBDA), België (Codex) en Luxemburg (ITM)?',
      answer: 'Alle drie de landen baseren zich op de Europese Richtlijn Drukapparatuur (PED 2014/68/EU) voor de fabricagefase, maar regelen de gebruiksfase nationaal. In Nederland geldt het Warenwetbesluit Drukapparatuur 2016 (WBDA) met toezicht door NL-CBI’s. In België geldt de Codex over het Welzijn op het Werk (Boek IV Titel 3) en het ARAB met keuringen door erkende EDTC’s (zoals Vinçotte, Apragaz). In Luxemburg geldt het Règlement grand-ducal van 23 december 1999 met registratie bij de ITM (Inspection du Travail et des Mines) en keuringen door Organismes Agréés (zoals Luxcontrol).',
    },
    {
      id: 'faq-2',
      category: 'Techniek',
      question: 'Wat houdt de 2-liter grens in volgens de Europese PED-richtlijn 2014/68/EU?',
      answer: 'Bij stoom- en oververhitwaterinstallaties boven 110 °C en 31,25 bar bepaalt het waterinhoudsvolume van 2 liter de risicoclassificatie. Apparatuur met een inhoud tot 2 liter valt onder Artikel 4 lid 3 (Goed Vakmanschap / SEP) en is vrijgesteld van periodieke keuringen. Apparatuur boven de 2 liter valt in de zwaarste Europese klasse: PED Categorie IV.',
    },
    {
      id: 'faq-3',
      category: 'Keuringen',
      question: 'Wat is een Keuring voor Ingebruikneming (KvI / Indienststellingsonderzoek)?',
      answer: 'Een KvI (Nederland, art. 21 WBDA 2016) of indienststellingsonderzoek (België, Codex Boek IV) is een wettelijk verplichte keuring uitgevoerd door een geaccrediteerde inspectie-instelling vóórdat een Categorie IV installatie voor de eerste maal operationeel wordt ingezet.',
    },
    {
      id: 'faq-4',
      category: 'Keuringen',
      question: 'Hoe vaak moeten stoominstallaties in PED Categorie IV herkeurd worden?',
      answer: 'De herkeuringsinterval verschilt per land: in Nederland geldt onder het WBDA 2016 een tweejaarlijkse herkeuringstermijn (elke 24 maanden) door een NL-CBI. In België legt de Codex over het Welzijn op het Werk (Boek IV Titel 3) standaard een jaarlijkse herkeuring (elke 12 maanden) op door een erkende EDTC (zoals Vinçotte of Apragaz), tenzij onder specifieke voorwaarden verlenging is vergund. Ook in Duitsland en de VS/Canada gelden jaarlijkse uitwendige controles.',
    },
    {
      id: 'faq-5',
      category: 'Kosten & Onderdelen',
      question: 'Waarom mag ik op een Categorie IV hogedruktrailer geen universele hogedrukslangen monteren?',
      answer: 'Omdat een Categorie IV hogedruktrailer als één integraal samenstel (assembly) is gecertificeerd onder toezicht van een Notified Body. De typegoedkeuring omvat de specifieke brander/warmtewisselaar, veiligheden en hogedrukslangen. Het vervangen van een versleten slang door een kwalitatieve universele slang geldt juridisch als een ongeautoriseerde wijziging (Artikel 24 WBDA 2016). Hierdoor vervalt de CE-samenstelcertificering direct, is de hogedruktrailer illegaal in bedrijf en weigert de aansprakelijkheidsverzekering dekking bij calamiteiten.',
    },
    {
      id: 'faq-6',
      category: 'Handhaving & Boetes',
      question: 'Welke sancties legt de Arbeidsinspectie op bij controle van een ongekeurde hogedruktrailer?',
      answer: 'De toezichthouders – de Nederlandse Arbeidsinspectie (NLA), de Belgische FOD WASO en de Luxemburgse ITM – controleren actief op werven en bij gevel-, kauwgom- en industriële reiniging. Het in bedrijf hebben van een ongekeurde Categorie IV hogedruktrailer geldt als economisch delict en zwaar arbeidsmisdrijf. De inspecteur legt direct een bevel tot stillegging (verzegeling) op en schrijft een boete uit die oploopt tot tienduizenden euro’s.',
    },
    {
      id: 'faq-7',
      category: 'Regelgeving',
      question: 'Geldt de keuringsplicht voor een hogedruktrailer ook als de fabrikant al CE-markering heeft geleverd?',
      answer: 'Ja, absoluut. De CE-markering van de fabrikant toont uitsluitend aan dat de hogedruktrailer en de brander/warmtewisselaar zijn gefabriceerd conform de Europese productievoorschriften (PED Richtlijn 2014/68/EU). De gebruiksfase valt onder nationale wetgeving (WBDA 2016 in Nederland, Codex in België). Een CE-markering vervangt NOOIT de wettelijk verplichte Keuring voor Ingebruikneming (KvI) door een NL-CBI vóór eerste inzet.',
    },
    {
      id: 'faq-8',
      category: 'Aankoop & Verkoop',
      question: 'Wat moet u als koper bij de aankoop van een hogedruktrailer eigenlijk ook weten over de keuringsplicht?',
      answer: 'Tijdens het verkooptraject ligt de nadruk begrijpelijkerwijs op prestaties zoals werkdruk (bijv. 350 of 500 bar), watertemperatuur en reinigingscapaciteit. Wat u als koper eigenlijk ook moet weten, is dat een Categorie IV installatie (> 2 liter waterinhoud) specifieke operationele verplichtingen meebrengt: een verplichte Keuring voor Ingebruikneming (KvI), tweejaarlijkse periodieke herkeuringen en bijbehorende stilstand. Daarnaast vereist de typegoedkeuring het gebruik van gespecificeerde originele slangen en appendages. Door deze aspecten vooraf mee te wegen, krijgt u direct een realistisch beeld van de totale exploitatiekosten (TCO).',
    },
    {
      id: 'faq-9',
      category: 'Inspecties',
      question: 'Wie mag een Categorie IV hogedruktrailer keuren (NL-CBI vs. EDTC)?',
      answer: 'In Nederland mag de KvI en de 2-jaarlijkse herkeuring uitsluitend worden verricht door een aangewezen NL-CBI (zoals Kiwa, TÜV Nederland, Dekra of DNV). In België is dit voorbehouden aan een Externe Dienst voor Technische Controles (EDTC, zoals Vinçotte, BTV of Apragaz). Een gewone APK- of chassiskeuring of algemene NEN 3140 inspectie is wettelijk NIET geldig voor de drukhoudende stoominstallatie.',
    },
    {
      id: 'faq-10',
      category: 'Huur & Lease',
      question: 'Geldt de keuringsplicht ook bij het huren of leasen van een heetwater-hogedruktrailer?',
      answer: 'Ja, zonder uitzondering. Op grond van de Arbowetgeving (art. 7.4a) is elke werkgever die een arbeidsmiddel ter beschikking stelt aan werknemers hoofdelijk aansprakelijk voor de wettelijke veiligheidsstatus. Als u een hogedruktrailer huurt of leaset, moet u vooraf controleren of de geldige Verklaring van Ingebruikneming en het meest recente herkeuringsrapport fysiek in het machinedossier van de hogedruktrailer aanwezig zijn.',
    },
  ],
  checklist: [
    {
      id: 'chk-1',
      phase: 'Aanschaf & Offerte',
      title: 'Waterinhoud (V) van de brander/warmtewisselaar schriftelijk opvragen',
      description: 'Vraag de leverancier naar de exacte vloeistofinhoud in liters van de verwarmingsspiraal. Ligt deze strikt op maximaal 2 liter (keuringsvrij SEP) of erboven (> 2 liter = zware Categorie IV keuringsplicht)?',
      requirement: 'Art. 4.3 PED (SEP) vs. PED Categorie IV',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-2',
      phase: 'Aanschaf & Offerte',
      title: 'Ontwerpdruk (PS) en temperatuur (TS) van de hogedruktrailer vastleggen',
      description: 'Controleer of de maximale werkdruk (bijv. 200–500 bar) en watertemperatuur (> 110 °C stoom/oververhit water) vallen onder de wettelijke stoomketeldefinitie.',
      requirement: 'PED 2014/68/EU Bijlage II Tabel 5',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-3',
      phase: 'Aanschaf & Offerte',
      title: 'Onderdelenbeleid en merkplicht voor slangen en lansen verifiëren',
      description: 'Vraag de leverancier schriftelijk of vervanging van hogedrukslangen door gecertificeerde universele kwaliteitscomponenten is toegestaan zonder verval van CE/PED-samenstelcertificering.',
      requirement: 'WBDA 2016 Art. 24 / Belgische Codex (Risico Vendor Lock-in)',
      criticality: 'Aandachtspunt',
    },
    {
      id: 'chk-4',
      phase: 'Aanschaf & Offerte',
      title: 'Kosten voor 2-jaarlijkse herkeuring en stilstand van de hogedruktrailer budgetteren',
      description: 'Indien u kiest voor een hogedruktrailer met brander/warmtewisselaar > 2 liter: neem direct de periodieke inspectiekosten (ca. € 1.150 per 24 maanden) plus 2 dagen stilstand per beurt op in de vlootbegroting.',
      requirement: 'TCO Exploitatiebegroting & NL-CBI / EDTC Cyclus',
      criticality: 'Aanbevolen',
    },
    {
      id: 'chk-5',
      phase: 'Aflevering Hogedruktrailer',
      title: 'Typeplaatje van de hogedruktrailer controleren (CE + 4-cijferig NoBo nummer)',
      description: 'Bij een Categorie IV hogedruktrailer moet op het typeplaatje van het complete samenstel een 4-cijferig Notified Body nummer staan (bijv. 0036, 0029, 0620).',
      requirement: 'PED 2014/68/EU Art. 19 / WBDA Art. 8',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-6',
      phase: 'Aflevering Hogedruktrailer',
      title: 'EU-Conformiteitsverklaring voor het Totale Samenstel eisen',
      description: 'Eis een officiële EU-conformiteitsverklaring waarin het complete samenstel van de hogedruktrailer als Categorie IV is vrijgegeven, en weiger levering als er enkel losse verklaringen voor pomp of brander/warmtewisselaar zijn.',
      requirement: 'PED 2014/68/EU Module G of B+D/B+F Samenstelcertificaat',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-7',
      phase: 'Vóór Eerste Klus',
      title: 'Keuring voor Ingebruikneming (KvI) door NL-CBI / EDTC laten uitvoeren',
      description: 'Bij hogedruktrailers met brander/warmtewisselaar > 2 liter: Schakel vóór de eerste inzet op de weg of werf een NL-CBI (NL) of EDTC (BE) in voor de wettelijk verplichte opstellingskeuring en drukproef.',
      requirement: 'WBDA 2016 Art. 21 / Codex Boek IV Titel 3',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-8',
      phase: 'Vóór Eerste Klus',
      title: 'Veiligheidsventiel, breekplaat en thermische beveiliging controleren',
      description: 'Controleer de verzegeling van de veerbelaste veiligheidsklep en test de automatische brander/warmtewisselaar-uitschakeling bij watergebrek of overdruk conform NEN-EN 12952.',
      requirement: 'NEN-EN 12952 / WBDA & Codex Voorschriften',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-9',
      phase: 'Beheer & Vloot',
      title: 'Machinedossier en inspectierapporten in de hogedruktrailer bewaren',
      description: 'Plaats een waterdichte koker of map in de hogedruktrailer met de Verklaring van Ingebruikneming en het actuele inspectierapport voor eventuele inspecties door de Arbeidsinspectie.',
      requirement: 'Wettelijke Bewaarplicht & Bewijslast Arbeidsinspectie',
      criticality: 'Verplicht',
    },
    {
      id: 'chk-10',
      phase: 'Beheer & Vloot',
      title: '24-Maands herkeuringstermijn borgen in onderhoudsplanning',
      description: 'Plan minimaal 60 dagen voor het verstrijken van de 2-jaarstermijn de periodieke inspectie in bij een erkend keuringsinstituut om ongekeurde inzet en boetes te voorkomen.',
      requirement: 'WBDA 2016 Art. 22 / Belgische Codex Periodieke Inspectie',
      criticality: 'Verplicht',
    },
  ],
  common: {
    readMore: 'Lees volledige toelichting',
    downloadGuide: 'Download PDF Kennisgids',
    openDecisionTree: 'Open Keurings-Check',
    calculateTco: 'Naar TCO Calculator',
    contactNote: 'Heeft u specifieke juridische of technische vragen over uw machinepark?',
    sourceReferences: 'Officiële bronnen: Nederland (WBDA 2016 & Warenwetregeling), België (Codex Welzijn op het Werk Boek IV Titel 3 & ARAB art. 269–283ter), Luxemburg (Règlement grand-ducal stoomtoestellen & ITM), Europese Richtlijn 2014/68/EU (PED).',
    legalNotice: 'Aan de inhoud van dit kennisplatform kunnen geen juridische rechten worden ontleend. Raadpleeg bij twijfel een aangewezen keuringsinstantie (NL-CBI in NL, EDTC in BE, of Organisme agréé / ITM in LU).',
  },
};
