export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  region: 'europe' | 'north-america' | 'apac';
  regionLabel: string;
  law: string;
  standard: string;
  bodyType: string;
  bodies: string[];
  kviName: string;
  herkeuringTermijn: string;
  herkeuringDetails: string;
  twoLiterExemption: string;
  penalties: string;
  specificRisk: string;
  operatingCertificateName?: string;
}

export const COUNTRIES_NL: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Nederland',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Warenwetbesluit drukapparatuur 2016 (WBDA) & Warenwetregeling drukapparatuur 2016',
    standard: 'PED 2014/68/EU + PRDA Katern 1.3',
    bodyType: 'NL-CBI (Conformiteitsbeoordelingsinstantie)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Keuring voor Ingebruikneming (KvI) → Verklaring van Ingebruikneming (VVI)',
    herkeuringTermijn: 'Elke 2 jaar (24 maanden)',
    herkeuringDetails: 'Verplichte periodieke herkeuring met visueel inwendig/uitwendig onderzoek, hydrostatische druktest, beproeving van de veiligheidsklep en wanddiktemeting conform PRDA katern 1.3.',
    twoLiterExemption: 'Volledig vrijgesteld van KvI en herkeuring onder Artikel 4 lid 3 PED (SEP). Regulier werkgeversonderhoud conform Arbobesluit art. 7.4a.',
    penalties: 'Kwalificatie als economisch delict (WED art. 1a). Bevoegdheid Nederlandse Arbeidsinspectie (NLA) tot directe stillegging en bestuurlijke boetes tot tienduizenden euro’s.',
    specificRisk: 'Veel gebruikers verwarren fabrieks-CE met exploitatiegoedkeuring. Inzet zonder VVI is direct strafbaar.',
    operatingCertificateName: 'Verklaring van Ingebruikneming (VVI)'
  },
  {
    code: 'DE',
    name: 'Duitsland',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Betriebssicherheitsverordnung (BetrSichV) & TRBS (Technische Regeln für Betriebssicherheit)',
    standard: 'PED 2014/68/EU + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Zugelassene Überwachungsstelle)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Prüfung vor Inbetriebnahme (§ 15 BetrSichV) + Erlaubnispflicht (§ 18 BetrSichV)',
    herkeuringTermijn: '1 jaar (uitwendig) / 3 jaar (inwendig) / 6–9 jaar (druktest)',
    herkeuringDetails: 'Anhang 2 Abschnitt 4 BetrSichV: Äußere Prüfung (12 mnd), Innere Prüfung (max. 36 mnd), Festigkeitsprüfung (6 tot 9 jaar). Voor Cat. IV stoominstallaties is bovendien een officiële exploitatievergunning (Erlaubnis) van de Gewerbeaufsicht verplicht.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Geen erlaubnispflichtige stoominstallatie. Mag intern worden gekeurd door een "zur Prüfung befähigte Person" (bP) volgens TRBS 1203 zonder verplichte ZÜS-tussenkomst.',
    penalties: 'Overtreding van de BetrSichV is een Ordnungswidrigkeit (§ 22 BetrSichV) met boetes tot € 100.000,- of bij opzet/gevaarzetting een Straftat (§ 26 Chemikaliengesetz/ArbSchG).',
    specificRisk: 'In Duitsland geldt bij Categorie IV een vergunningsplicht (Erlaubnispflicht) vóór plaatsing. Zonder vergunning mag de machine de openbare weg of industriële site niet op.',
    operatingCertificateName: 'Erlaubnis der Gewerbeaufsicht / ZÜS Prüfbescheinigung'
  },
  {
    code: 'BE',
    name: 'België',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Codex over het welzijn op het werk (Boek IV, Titel 3) & KB van 18 oktober 1991 / 17 maart 2022',
    standard: 'PED 2014/68/EU + Belgische Codex',
    bodyType: 'EDTC (Externe Dienst voor Technische Controles)',
    bodies: ['Vinçotte', 'Normec BTV', 'Apragaz', 'OCB', 'Bureau Veritas BE'],
    kviName: 'Indienststellingsonderzoek door EDTC vóór eerste ingebruikname',
    herkeuringTermijn: 'Standaard jaarlijks (elke 12 maanden)',
    herkeuringDetails: 'Jaarlijks uitwendig onderzoek en verificatie van de afstelling van veiligheidskleppen. Periodiek inwendig onderzoek (verlengbaar onder strikte voorwaarden mits goedkeuring toezichthoudend ambtenaar voor stoomgeneratoren van de 4e groep).',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Vrijgesteld van specifieke stoomketel-keuring door EDTC. Valt onder algemene risicoanalyse en periodieke controle van arbeidsmiddelen.',
    penalties: 'Toezicht door FOD Werkgelegenheid, Arbeid en Sociaal Overleg (FOD WASO / Toezicht op het Welzijn op het Werk). Boetes en strafsancties via het Sociaal Strafwetboek.',
    specificRisk: 'België hanteert een zeer strikte jaarlijkse controle op stoomgeneratoren. Nederlandse bedrijven die in Vlaanderen of Wallonië werken worden hier frequent op aangesproken.',
    operatingCertificateName: 'EDTC Indienststellingsverslag & Jaarlijks Keuringsverslag'
  },
  {
    code: 'LU',
    name: 'Luxemburg',
    flag: '🇱🇺',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Règlement grand-ducal du 23 décembre 1999 (appareils à vapeur et à gaz) & Code du Travail (Livre III)',
    standard: 'PED 2014/68/EU + ITM-voorschriften',
    bodyType: 'Organisme Agréé (erkend keuringsorganisme)',
    bodies: ['Luxcontrol S.A.', 'TÜV Rheinland Luxembourg', 'APAVE Luxembourg', 'SGS Luxembourg'],
    kviName: 'Réception avant mise en service & Verplichte aanmelding ITM',
    herkeuringTermijn: 'Periodiek conform ITM-termijnen (elke 12-24 maanden)',
    herkeuringDetails: 'Keuring van de drukontlasting, veiligheidskleppen, afblazen en wanddikte. Verplichte registratie in het centrale ITM-veiligheidsdossier.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP / Sound Engineering Practice): Vrijgesteld van het zware ITM-registratiedossier en de formele réception avant mise en service.',
    penalties: 'Toezicht door de Inspection du Travail et des Mines (ITM). Bevoegdheid tot directe stillegging (arrêt immédiat), verzegeling ter plaatse en strafrechtelijke vervolging.',
    specificRisk: 'In Luxemburg treden ITM-inspecteurs streng op. Zonder goedgekeurd dossier van een erkend controleorganisme (zoals Luxcontrol) mag de machine niet op de werf worden ingezet.',
    operatingCertificateName: 'Rapport de réception ITM / Certificat de contrôle périodique'
  },
  {
    code: 'FR',
    name: 'Frankrijk',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Arrêté du 20 novembre 2017 relatif au suivi en service des ESP & Code de l\'environnement',
    standard: 'PED 2014/68/EU + CODAP / CTP',
    bodyType: 'Organisme Habilité (OH)',
    bodies: ['APAVE', 'Bureau Veritas France', 'DEKRA Industrial FR', 'SOCOTEC', 'CETIM'],
    kviName: 'Contrôle de mise en service (CMS) & Déclaration de mise en service (DMS)',
    herkeuringTermijn: 'Elke 2 jaar (24 maanden) IP / 10 jaar RP',
    herkeuringDetails: 'Inspection périodique (IP) uiterlijk elke 24 maanden voor "générateurs de vapeur". Requalification périodique (RP) met hydraulische herkeuring elke 10 jaar.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Uitdrukkelijk vrijgesteld van Déclaration de mise en service en periodieke inspecties door Organismes Habilités.',
    penalties: 'Handhaving door de DREAL / Inspection du travail. Overtredingen vallen onder het Code de l\'environnement met zware administratieve en strafrechtelijke sancties.',
    specificRisk: 'Zonder voorafgaande "Déclaration de mise en service" via het Franse overheidsloket LUNE mag een Categorie IV installatie niet operationeel worden gebruikt.',
    operatingCertificateName: 'Récépissé de Déclaration de Mise en Service (DMS) via LUNE'
  },
  {
    code: 'UK',
    name: 'Verenigd Koninkrijk',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europa (Non-EU)',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 - Statutory Instrument 2000 No. 168)',
    standard: 'PER 2016 / UKCA + SAFed Guidelines',
    bodyType: 'Competent Person (SAFed Accredited Inspection Bodies)',
    bodies: ['Allianz Engineering', 'Zurich Engineering', 'Bureau Veritas UK', 'British Engineering Services', 'TÜV SÜD UK'],
    kviName: 'Written Scheme of Examination (WSE) + Initial Inspection',
    herkeuringTermijn: 'Elke 12 tot 14 maanden (Jaarlijks)',
    herkeuringDetails: 'PSSR regels vereisen dat stoominstallaties worden gekeurd volgens een formeel Written Scheme of Examination (WSE). Voor stoomtoestellen wordt de intervaltermijn nagenoeg universeel vastgelegd op 12 tot 14 maanden door de Competent Person.',
    twoLiterExemption: 'Voor SEP / kleine volumes (onder 250 bar-liter of waterinhoud onder drempelwaarden) geldt geen verplichting voor een complex stoomketel-WSE.',
    penalties: 'Handhaving door de Health and Safety Executive (HSE) onder de Health and Safety at Work Act 1974; Improvement en Prohibition Notices met onbeperkte boetes.',
    specificRisk: 'Werken in het VK met mobiele stoomcleaners vereist voorafgaande validatie van het WSE door een Britse Competent Person.',
    operatingCertificateName: 'Certificate of Examination under WSE'
  },
  {
    code: 'CH',
    name: 'Zwitserland',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europa (Non-EU)',
    law: 'SR 832.30 (VUV - Unfallverhütungsverordnung) & EKAS Richtlinie 6516 (Druckbehälter)',
    standard: 'MRA EU-CH (PED 2014/68/EU equivalent) + SVTI Vorschriften',
    bodyType: 'SVTI / ASIT (Schweizerischer Verein für technische Inspektionen)',
    bodies: ['SVTI Kesselinspektorat', 'SUVA (Schweizerische Unfallversicherung)', 'DEKRA Schweiz'],
    kviName: 'Erstprüfung und Bewilligung zur Inbetriebnahme durch das SVTI Kesselinspektorat',
    herkeuringTermijn: '1 tot 2 jaar (jaarlijks voor gestookte stoomketels)',
    herkeuringDetails: 'Gestookte stoomketels en stoomgeneratoren worden periodiek geïnspecteerd door het SVTI Kesselinspektorat. Uitwendige inspectie en veiligheidskleppen jaarlijks; inwendig elke 2 tot 3 jaar.',
    twoLiterExemption: 'Via de bilaterale akkoorden (MRA) erkent Zwitserland PED Art. 4 lid 3 (Gute Ingenieurpraxis). Toestellen onder 2 liter vallen buiten de verplichte SVTI-kesselkeuringen.',
    penalties: 'Controles door SUVA en kantonale arbeidsinspecties. Stillegging en boetes conform het Zwitserse Unfallversicherungsgesetz (UVG).',
    specificRisk: 'Zwitserse douane en SUVA controleren streng bij de grens en op bouwlocaties op het SVTI-keuringsboek.',
    operatingCertificateName: 'SVTI Betriebsbewilligung / Kesselprüfbuch'
  },
  {
    code: 'US',
    name: 'Verenigde Staten (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'Noord-Amerika',
    law: 'State Boiler & Pressure Vessel Safety Acts (bijv. Texas TDLR Ch. 755, Cal/OSHA Title 8, Ohio BBS, NY DOL)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2: Inspection)',
    bodyType: 'National Board Commissioned Inspector (State / Authorized Insurance AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Inspection Bureaus'],
    kviName: 'Initial Inspection & First Operating Certificate Issuance (State Boiler Division)',
    herkeuringTermijn: 'Standaard jaarlijks (elke 12 maanden)',
    herkeuringDetails: 'NBIC NB-23 Part 2 (In-service Inspection) & staatsstatuut vereisen een jaarlijkse externe en interne inspectie van "Power Boilers" (stoom > 15 psi of water > 160 psi / 250°F). Bevat afdichting van het ASME/NB UV-veiligheidsventiel en uitgifte van een nieuw Certificate of Operation.',
    twoLiterExemption: 'Uitzonderingen via "Coil-Type Forced Circulation Steam Generators without a Drum": De meeste staten (en ASME Sec. I PEB/PMB) stellen doorstroom-branders/warmtewisselaars met spiraal vrij van de zware ketel-inspectie mits de waterinhoud van de spiraal onder statelijke drempels blijft (vaak < 5 US gallons / ~19 liter, of miniatuurketels < 16 inch diameter). Daarboven geldt direct de jaarlijkse staatskeuring.',
    penalties: 'Exploitatie zonder geldig "Certificate of Operation" is een misdrijf/overtreding onder State Labor Codes. Boetes tot $1.000+ per dag, rode vergrendeling ("Red Tagging") en direct vervallen van de aansprakelijkheidsdekking bij claims.',
    specificRisk: 'Elke Amerikaanse staat heeft zijn eigen Chief Boiler Inspector en staatsnummering (State Tag). Wie met Europese apparatuur in de VS werkt zonder ASME-stempel en National Board registratie loopt het risico op directe inbeslagname.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'Noord-Amerika',
    law: 'Provincial Safety Codes Acts (Ontario TSSA O. Reg. 220/01, Alberta ABSA AB-506, BC Technical Safety)',
    standard: 'CSA B51 (Boiler, Pressure Vessel, and Pressure Piping Code)',
    bodyType: 'Provincial Safety Authorities (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Quebec)'],
    kviName: 'CRN (Canadian Registration Number) Verificatie & Initial Operating Permit',
    herkeuringTermijn: 'Jaarlijks (elke 12 maanden) voor High-Pressure Boilers',
    herkeuringDetails: 'CSA B51 en provinciale verordeningen (zoals TSSA Act) leggen vast dat hogedrukstoomketels jaarlijks gekeurd moeten worden om het Certificate of Inspection (COI) te verlengen. Overige drukvaten volgen een 3- tot 5-jarige cyclus.',
    twoLiterExemption: 'Kleine branders/warmtewisselaars van het spoeltype ("Coil type steam generators") met beperkte waterinhoud (< 3 tot 5 gallons afhankelijk van de provincie) vallen onder vrijstellingen voor stoomketeloperators, mits de drukdelen een geldig Canadees Registratienummer (CRN) bezitten.',
    penalties: 'Provincial Safety Orders, onmiddellijke verzegeling van de apparatuur en gerechtelijke boetes via provinciale rechtbanken conform de Safety Codes Act.',
    specificRisk: 'Zonder geldig provinciaal CRN-nummer mag in Canada GEEN ENKEL drukvat worden verkocht of in werking gesteld, ongeacht CE- of ASME-certificering.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australië & Nieuw-Zeeland',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Azië-Pacific',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria, SafeWork QLD)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343 (Hazard Levels)',
    bodyType: 'Competent In-Service Inspection Bodies (NATA Accredited / SafeWork Recognised)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'Heng Sheng / In-Service Inspections'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Jaarlijks (12 mnd) extern / 2 jaar inwendig voor gestookte stoomketels',
    herkeuringDetails: 'Tabel 4.1 van AS/NZS 3788 schrijft voor gestookte stoomgeneratoren van Hazard Level A, B en C een jaarlijkse externe inspectie voor en minimaal tweejaarlijkse inwendige inspecties met afpersen van overdrukinrichtingen.',
    twoLiterExemption: 'Apparatuur geclassificeerd als Hazard Level E (zeer laag risico op grond van AS 4343, waar volume en druk onder de drempelwaarden vallen) is vrijgesteld van periodieke registratie bij de staat.',
    penalties: 'Handhaving door SafeWork. Hoge boetes onder de WHS Act (tot AU$ 3.000.000,- voor rechtspersonen bij ernstige veiligheidsovertredingen).',
    specificRisk: 'Australië vereist voorafgaande "Design Registration" bij de staatsautoriteit voordat een stoomtoestel het land in mag.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];

export const COUNTRIES_EN: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Commodities Act Decree on Pressure Equipment 2016 (WBDA 2016) & Commodities Act Regulation',
    standard: 'PED 2014/68/EU + PRDA Section 1.3',
    bodyType: 'NL-CBI (Conformity Assessment Body)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Pre-Commissioning Inspection (KvI) → Declaration of In-Service Authorization (VVI)',
    herkeuringTermijn: 'Every 2 years (24 months)',
    herkeuringDetails: 'Mandatory periodic recertification with internal and external visual examination, hydrostatic pressure test, safety relief valve bench testing, and ultrasonic wall thickness measurements under PRDA Section 1.3.',
    twoLiterExemption: 'Fully exempt from pre-commissioning examination (KvI) and periodic recertification under Article 4(3) PED (SEP). Standard employer workplace safety maintenance applies (Working Conditions Decree art. 7.4a).',
    penalties: 'Classified as an economic offence (Economic Offences Act Art. 1a). The Netherlands Labour Inspectorate (NLA) has authority for immediate operational stop-work orders and administrative fines up to tens of thousands of euros.',
    specificRisk: 'Many operators confuse manufacturer CE marking with operational in-service authorization. Operating Category IV equipment without a valid VVI is a direct statutory offence.',
    operatingCertificateName: 'Declaration of In-Service Authorization (VVI)'
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Industrial Safety Regulation (Betriebssicherheitsverordnung - BetrSichV) & TRBS Rules',
    standard: 'PED 2014/68/EU + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Approved Inspection Body)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Pre-commissioning Inspection (§ 15 BetrSichV) + Mandatory Operating Permit (§ 18 BetrSichV)',
    herkeuringTermijn: '1 year (external) / 3 years (internal) / 6–9 years (strength test)',
    herkeuringDetails: 'Annex 2 Section 4 BetrSichV: External audit (12 months), Internal inspection (max. 36 months), Strength/hydrostatic test (6 to 9 years). Category IV steam assemblies also require an official operating permit (Erlaubnis) from the Trade Supervisory Authority (Gewerbeaufsicht).',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Not an installation subject to mandatory permit (Erlaubnis). Can be inspected in-house by an authorized competent person (zur Prüfung befähigte Person - bP) in accordance with TRBS 1203 without mandatory ZÜS involvement.',
    penalties: 'Violation of BetrSichV constitutes an administrative offence (§ 22 BetrSichV) with fines up to € 100,000, or a criminal offence in cases of intent or endangerment (§ 26 ChemG / ArbSchG).',
    specificRisk: 'In Germany, Category IV requires an official operating permit (Erlaubnispflicht) before installation. Without a permit, the machine may not be deployed on public roads or industrial sites.',
    operatingCertificateName: 'Gewerbeaufsicht Operating Permit / ZÜS Inspection Certificate'
  },
  {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Code of Well-being at Work (Book IV, Title 3) & Royal Decrees of 18 Oct 1991 / 17 Mar 2022',
    standard: 'PED 2014/68/EU + Belgian Code of Well-being',
    bodyType: 'EDTC (External Service for Technical Controls)',
    bodies: ['Vinçotte', 'Normec BTV', 'Apragaz', 'OCB', 'Bureau Veritas BE'],
    kviName: 'Commissioning examination by an accredited EDTC prior to first operation',
    herkeuringTermijn: 'Standard annual (every 12 months)',
    herkeuringDetails: 'Annual external examination and calibration verification of safety relief valves. Periodic internal examination (extendable under strict conditions with supervisory authority approval for 4th group steam generators).',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Exempt from specific steam boiler inspection by an EDTC. Governed by general risk assessment and periodic work equipment checks.',
    penalties: 'Supervised by the FPS Employment, Labour and Social Dialogue (FPS WASO). Substantial administrative and criminal penalties under the Social Penal Code.',
    specificRisk: 'Belgium enforces a strict annual inspection regime for steam generators. Cross-border contractors from neighboring countries are frequently audited.',
    operatingCertificateName: 'EDTC Commissioning Report & Annual Inspection Certificate'
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    flag: '🇱🇺',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Grand-Ducal Regulation of 23 Dec 1999 (Steam & Gas Appliances) & Labour Code (Book III)',
    standard: 'PED 2014/68/EU + ITM Requirements',
    bodyType: 'Organisme Agréé (Accredited Inspection Body)',
    bodies: ['Luxcontrol S.A.', 'TÜV Rheinland Luxembourg', 'APAVE Luxembourg', 'SGS Luxembourg'],
    kviName: 'Pre-commissioning acceptance (Réception avant mise en service) & Mandatory ITM notification',
    herkeuringTermijn: 'Periodic per ITM schedule (every 12–24 months)',
    herkeuringDetails: 'Examination of pressure relief systems, safety valves, venting lines, and wall thickness. Mandatory registration in the central ITM safety registry.',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Exempt from heavy ITM dossier registration and formal pre-commissioning acceptance (réception avant mise en service).',
    penalties: 'Enforced by the Inspectorate of Labour and Mines (ITM). Authority for immediate stop-work orders (arrêt immédiat), on-site sealing, and judicial prosecution.',
    specificRisk: 'ITM inspectors enforce strict compliance in Luxembourg. Without an approved dossier from an accredited inspection body (such as Luxcontrol), equipment cannot be deployed on job sites.',
    operatingCertificateName: 'ITM Acceptance Report / Periodic Inspection Certificate'
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Decree of 20 November 2017 on In-Service Monitoring of Pressure Equipment & Environmental Code',
    standard: 'PED 2014/68/EU + CODAP / CTP',
    bodyType: 'Organisme Habilité (OH - Authorized Inspection Body)',
    bodies: ['APAVE', 'Bureau Veritas France', 'DEKRA Industrial FR', 'SOCOTEC', 'CETIM'],
    kviName: 'Commissioning Control (CMS) & Commissioning Declaration (DMS via LUNE)',
    herkeuringTermijn: 'Every 2 years (24 months) for IP / 10 years for RP',
    herkeuringDetails: 'Periodic inspection (IP) at least every 24 months for "steam generators". Periodic requalification (RP) including hydraulic pressure testing every 10 years.',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Expressly exempt from Commissioning Declaration (DMS) and periodic inspections by Authorized Bodies (Organismes Habilités).',
    penalties: 'Enforcement by DREAL / Labour Inspectorate. Violations fall under the Environmental Code with severe administrative and criminal sanctions.',
    specificRisk: 'Without prior Commissioning Declaration (DMS) registered via the French government portal LUNE, Category IV equipment cannot be operated legally.',
    operatingCertificateName: 'Receipt of Commissioning Declaration (DMS) via LUNE'
  },
  {
    code: 'UK',
    name: 'United Kingdom',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europe (Non-EU)',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 - Statutory Instrument 2000 No. 168)',
    standard: 'PER 2016 / UKCA + SAFed Guidelines',
    bodyType: 'Competent Person (SAFed Accredited Inspection Bodies)',
    bodies: ['Allianz Engineering', 'Zurich Engineering', 'Bureau Veritas UK', 'British Engineering Services', 'TÜV SÜD UK'],
    kviName: 'Written Scheme of Examination (WSE) + Initial Inspection',
    herkeuringTermijn: 'Every 12 to 14 months (Annual)',
    herkeuringDetails: 'PSSR regulations require steam installations to be examined in accordance with a formal Written Scheme of Examination (WSE). For steam equipment, the interval is almost universally established at 12 to 14 months by the Competent Person.',
    twoLiterExemption: 'For SEP / micro-volumes (under 250 bar-litres or below water volume thresholds), there is no statutory obligation for a complex steam boiler WSE.',
    penalties: 'Enforcement by the Health and Safety Executive (HSE) under the Health and Safety at Work etc. Act 1974; Improvement and Prohibition Notices with unlimited fines.',
    specificRisk: 'Operating mobile steam cleaners in the UK requires prior validation of the WSE by a UK certified Competent Person.',
    operatingCertificateName: 'Certificate of Examination under WSE'
  },
  {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europe (Non-EU)',
    law: 'SR 832.30 (VUV - Accident Prevention Ordinance) & EKAS Guideline 6516 (Pressure Vessels)',
    standard: 'MRA EU-CH (PED 2014/68/EU equivalent) + SVTI Regulations',
    bodyType: 'SVTI / ASIT (Swiss Association for Technical Inspections)',
    bodies: ['SVTI Boiler Inspectorate', 'SUVA (Swiss National Accident Insurance)', 'DEKRA Switzerland'],
    kviName: 'Initial inspection and operating permit by the SVTI Boiler Inspectorate',
    herkeuringTermijn: '1 to 2 years (annual for fired steam boilers)',
    herkeuringDetails: 'Fired steam boilers and steam generators are periodically inspected by the SVTI Boiler Inspectorate. External inspection and safety relief valve testing annually; internal inspection every 2 to 3 years.',
    twoLiterExemption: 'Under bilateral agreements (MRA), Switzerland recognizes PED Art. 4(3) (Sound Engineering Practice). Units under 2 litres fall outside mandatory SVTI boiler audits.',
    penalties: 'Inspections by SUVA and cantonal labor inspectorates. Shutdown and fines under the Swiss Accident Insurance Act (UVG).',
    specificRisk: 'Swiss customs and SUVA strictly verify the SVTI boiler inspection logbook at the border and on construction sites.',
    operatingCertificateName: 'SVTI Operating Permit / Boiler Inspection Logbook'
  },
  {
    code: 'US',
    name: 'United States (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'North America',
    law: 'State Boiler & Pressure Vessel Safety Acts (e.g., Texas TDLR Ch. 755, Cal/OSHA Title 8, Ohio BBS, NY DOL)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2: Inspection)',
    bodyType: 'National Board Commissioned Inspector (State / Authorized Insurance AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Inspection Bureaus'],
    kviName: 'Initial Inspection & First Operating Certificate Issuance (State Boiler Division)',
    herkeuringTermijn: 'Standard annual (every 12 months)',
    herkeuringDetails: 'NBIC NB-23 Part 2 (In-service Inspection) & state statutes require annual external and internal inspection of "Power Boilers" (steam > 15 psi or water > 160 psi / 250°F). Includes testing/sealing of ASME/NB UV safety relief valves and issuance of a new Certificate of Operation.',
    twoLiterExemption: 'Exemption via "Coil-Type Forced Circulation Steam Generators without a Drum": Most states (and ASME Sec. I PEB/PMB) exempt continuous-flow coil cleaners from heavy boiler inspection provided water volume remains below state thresholds (often < 5 US gallons / ~19 litres, or miniature boilers < 16" dia). Exceeding this triggers annual state inspection.',
    penalties: 'Operating without a valid "Certificate of Operation" is a misdemeanor/violation under State Labor Codes. Fines up to $1,000+ per day, "Red Tagging" (lockout), and immediate invalidation of liability coverage.',
    specificRisk: 'Each US state has its own Chief Boiler Inspector and state numbering system (State Tag). Deploying European equipment in the US without ASME stamp and National Board registration risks immediate seizure.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'North America',
    law: 'Provincial Safety Codes Acts (Ontario TSSA O. Reg. 220/01, Alberta ABSA AB-506, BC Technical Safety)',
    standard: 'CSA B51 (Boiler, Pressure Vessel, and Pressure Piping Code)',
    bodyType: 'Provincial Safety Authorities (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Quebec)'],
    kviName: 'CRN (Canadian Registration Number) Verification & Initial Operating Permit',
    herkeuringTermijn: 'Annual (every 12 months) for High-Pressure Boilers',
    herkeuringDetails: 'CSA B51 and provincial regulations (such as TSSA Act) mandate annual inspections for high-pressure steam boilers to renew the Certificate of Inspection (COI). Other pressure vessels follow 3- to 5-year cycles.',
    twoLiterExemption: 'Small coil-type steam generators with limited water volume (< 3 to 5 gallons depending on province) fall under operator exemptions, provided pressure parts possess a valid Canadian Registration Number (CRN).',
    penalties: 'Provincial Safety Orders, immediate equipment sealing, and judicial fines via provincial courts under the Safety Codes Act.',
    specificRisk: 'Without a valid provincial CRN, NO pressure vessel may be sold or operated in Canada, regardless of CE or ASME certification.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australia & New Zealand',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Asia-Pacific',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria, SafeWork QLD)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343 (Hazard Levels)',
    bodyType: 'Competent In-Service Inspection Bodies (NATA Accredited / SafeWork Recognised)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'Heng Sheng / In-Service Inspections'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Annual (12 mos) external / 2 years internal for fired steam boilers',
    herkeuringDetails: 'Table 4.1 of AS/NZS 3788 prescribes annual external inspections and at least biennial internal inspections with pressure relief testing for Hazard Level A, B, and C fired steam generators.',
    twoLiterExemption: 'Equipment classified as Hazard Level E (negligible risk under AS 4343, where volume and pressure fall below thresholds) is exempt from periodic state registration.',
    penalties: 'Enforcement by SafeWork. Heavy fines under the WHS Act (up to AU$ 3,000,000 for corporations for category 1 safety offences).',
    specificRisk: 'Australia requires prior "Design Registration" with state authorities before any steam appliance can enter the country.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];

export const COUNTRIES_FR: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Pays-Bas',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Warenwetbesluit drukapparatuur 2016 (WBDA) & Warenwetregeling',
    standard: 'DESP 2014/68/UE + PRDA Fascicule 1.3',
    bodyType: 'NL-CBI (Organisme d’Évaluation de la Conformité)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Contrôle avant Mise en Service (KvI) → Déclaration d’Autorisation (VVI)',
    herkeuringTermijn: 'Tous les 2 ans (24 mois)',
    herkeuringDetails: 'Réépreuve périodique obligatoire avec visite interne/externe, épreuve hydrostatique, tarage des soupapes et mesure ultrasonique d’épaisseur.',
    twoLiterExemption: 'Totalement exempté de KvI et de réépreuve périodique sous l’Article 4 § 3 DESP (Règles de l’Art). Entretien employeur classique conforme à l’Arbobesluit art. 7.4a.',
    penalties: 'Infraction pénale économique (WED art. 1a). Arrêt immédiat par l’Inspection du Travail néerlandaise (NLA) et amendes administratives pouvant atteindre plusieurs dizaines de milliers d’euros.',
    specificRisk: 'Confusion fréquente entre marquage CE usine et autorisation d’exploitation. L’utilisation sans VVI est pénalement répréhensible.',
    operatingCertificateName: 'Déclaration d’Autorisation de Mise en Service (VVI)'
  },
  {
    code: 'DE',
    name: 'Allemagne',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Betriebssicherheitsverordnung (BetrSichV) & TRBS (Règles Techniques)',
    standard: 'DESP 2014/68/UE + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Organisme Agréé de Surveillance)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Prüfung vor Inbetriebnahme (§ 15 BetrSichV) + Erlaubnispflicht (§ 18 BetrSichV)',
    herkeuringTermijn: '1 an (externe) / 3 ans (interne) / 6–9 ans (pression)',
    herkeuringDetails: 'Anhang 2 Abschnitt 4 BetrSichV : Contrôle externe (12 mois), interne (max. 36 mois), épreuve de résistance (6 à 9 ans). Autorisation officielle d’exploiter requise pour les générateurs Cat. IV.',
    twoLiterExemption: 'Moins de 2 litres (Art. 4 § 3 Règles de l’Art) : Dispensé d’autorisation d’exploitation. Contrôle interne réalisable par une personne qualifiée (bP) selon TRBS 1203 sans recours obligatoire à une ZÜS.',
    penalties: 'Contravention (§ 22 BetrSichV) avec amendes jusqu’à 100 000 € ou délit pénal en cas de mise en danger intentionnelle (§ 26 Chemikaliengesetz/ArbSchG).',
    specificRisk: 'En Allemagne, obligation d’autorisation préalable (Erlaubnispflicht) avant installation pour la Catégorie IV.',
    operatingCertificateName: 'Erlaubnis der Gewerbeaufsicht / ZÜS Prüfbescheinigung'
  },
  {
    code: 'BE',
    name: 'Belgique',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Codex sur le bien-être au travail, Livre IV, Titre 3 (Équipements de travail)',
    standard: 'DESP 2014/68/UE + Normes harmonisées EN 12952 / EN 13445',
    bodyType: 'SECT (Service Externe pour les Contrôles Techniques)',
    bodies: ['Vinçotte', 'BTV Control', 'Apragaz', 'Bureau Veritas BE', 'OCB'],
    kviName: 'Contrôle de Réception avant Première Mise en Service (Livre IV Art. IV.3-13)',
    herkeuringTermijn: 'Annuel (tous les 12 mois)',
    herkeuringDetails: 'Contrôle périodique annuel obligatoire par un SECT agréé comprenant examen visuel, contrôle des organes de régulation et sécurité, et épreuve hydrostatique périodique.',
    twoLiterExemption: 'Équipements ≤ 2 litres : Classés sous l’Article 4 § 3 DESP. Dispensés du statut de chaudière à vapeur lourde du Codex. Contrôle de routine standard sans intervention requise d’un SECT.',
    penalties: 'Contrôles par l’Inspection du Travail (Direction Générale Contrôle du Bien-être au travail). Procès-verbal pénal et arrêt immédiat du chantier.',
    specificRisk: 'La législation belge impose une inspection annuelle rigoureuse dès que le volume dépasse 2 litres.',
    operatingCertificateName: 'Rapport de Contrôle de Mise en Service SECT'
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Arrêté ministériel du 20 novembre 2017 relatif au suivi en service des équipements sous pression',
    standard: 'DESP 2014/68/UE + CTP Chaudières',
    bodyType: 'Organisme Habilité (OH / APAVE, SOCOTEC, DEKRA, Bureau Veritas)',
    bodies: ['APAVE', 'SOCOTEC', 'Bureau Veritas France', 'DEKRA Industrial France', 'TÜV Rheinland France'],
    kviName: 'Déclaration de Mise en Service (DMS) & Contrôle de Mise en Service (CMS)',
    herkeuringTermijn: 'Inspection périodique : 18 à 24 mois / Recalification : 5 à 10 ans',
    herkeuringDetails: 'Articles 14 à 24 de l’Arrêté du 20/11/2017 : Contrôle de mise en service obligatoire, inspections régulières et requalification périodique avec épreuve hydraulique.',
    twoLiterExemption: 'Moins de 2 litres : Exemption totale de la DMS, du CMS et du régime de requalification périodique au titre de l’Article 4 § 3 DESP.',
    penalties: 'Mise en demeure par la DREAL, amendes administratives et sanctions pénales du Code de l’Environnement (Art. L. 557-55).',
    specificRisk: 'Déclaration obligatoire sur l’application gouvernementale LUNE pour tout matériel > 2L avant mise en service.',
    operatingCertificateName: 'Récépissé de Déclaration de Mise en Service (DMS) & Attestation CMS'
  },
  {
    code: 'UK',
    name: 'Royaume-Uni (UK)',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 / SI 2000 No. 128)',
    standard: 'UKCA / PE(S)R 2016 + BS EN 12952',
    bodyType: 'Competent Person / Inspection Bodies (UKAS Accredited)',
    bodies: ['Allianz Engineering', 'Bureau Veritas UK', 'HSB UK', 'Zurich Engineering', 'British Engineering Services'],
    kviName: 'Written Scheme of Examination (WSE) & Pre-Operational Sign-off',
    herkeuringTermijn: '12 à 14 mois (chaudières à vapeur)',
    herkeuringDetails: 'Règlement 8 et 9 du PSSR 2000 : Établissement obligatoire d’un Written Scheme of Examination (WSE) par une personne compétente certifiée UKAS.',
    twoLiterExemption: 'Sous PSSR 2000 Réglementation 4 : Les systèmes de faible volume à passage direct sans réservoir accumulateur bénéficient d’exemptions partielles du WSE.',
    penalties: 'Health and Safety Executive (HSE) : Improvement Notices, Prohibition Notices et condamnations pénales.',
    specificRisk: 'Exploiter un nettoyeur vapeur sans WSE valide constitue une infraction directe à la législation britannique.',
    operatingCertificateName: 'Certificate of Examination under Written Scheme (WSE)'
  },
  {
    code: 'CH',
    name: 'Suisse',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Ordonnance sur les appareils sous pression (OASP / RS 832.312.12)',
    standard: 'DESP 2014/68/UE + Règles SVTI',
    bodyType: 'ASIT (Association Suisse d’Inspection Technique) / SVTI',
    bodies: ['ASIT (SVTI) Kesselinspektorat', 'Inspecteurs cantonaux'],
    kviName: 'Autorisation d’Exploitation ASIT & Inscription au Registre',
    herkeuringTermijn: '1 à 2 ans (annuel pour chaudières à vapeur)',
    herkeuringDetails: 'Contrôle périodique par l’ASIT : Examen externe annuel des sécurités et interne tous les 2 à 3 ans.',
    twoLiterExemption: 'Reconnaissance bilatérale de l’Art. 4 § 3 DESP. Les générateurs ≤ 2 litres sont exemptés des contrôles de l’ASIT.',
    penalties: 'Contrôles SUVA et inspection du travail cantonale. Arrêt immédiat et poursuites selon la LAA.',
    specificRisk: 'Contrôles stricts de la SUVA et des douanes suisses aux frontières.',
    operatingCertificateName: 'Autorisation d’Exploitation ASIT / Livret de Chaudière'
  },
  {
    code: 'US',
    name: 'États-Unis (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'Amérique du Nord',
    law: 'State Boiler & Pressure Vessel Safety Acts (ex. Texas TDLR Ch. 755, Cal/OSHA Title 8)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2)',
    bodyType: 'National Board Commissioned Inspector (État / Assurances AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Bureaus'],
    kviName: 'Initial Inspection & Operating Certificate Issuance (State Boiler Division)',
    herkeuringTermijn: 'Annuel (tous les 12 mois)',
    herkeuringDetails: 'NBIC NB-23 Partie 2 : Contrôle annuel externe et interne des générateurs sous pression (« Power Boilers ») avec délivrance du Certificate of Operation.',
    twoLiterExemption: 'Exemption « Coil-Type Forced Circulation Steam Generators » : La majorité des États exemptent les serpentins continus sans ballon si le volume d’eau reste sous les seuils réglementaires.',
    penalties: 'Amendes journalières supérieures à 1 000 $, scellé rouge (« Red Tagging ») et nullité totale de la couverture d’assurance.',
    specificRisk: 'Chaque État dispose de son propre Chief Boiler Inspector et exige un enregistrement State Tag.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'Amérique du Nord',
    law: 'Provincial Safety Codes Acts (Ontario TSSA, Alberta ABSA, BC Technical Safety)',
    standard: 'CSA B51 (Code des chaudières, appareils et tuyauteries sous pression)',
    bodyType: 'Autorités Provinciales de Sécurité (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Québec)'],
    kviName: 'Enregistrement CRN & Permis d’Exploitation Initial',
    herkeuringTermijn: 'Annuel (tous les 12 mois) pour générateurs haute pression',
    herkeuringDetails: 'La norme CSA B51 et les décrets provinciaux imposent un contrôle annuel pour renouveler le Certificate of Inspection (COI).',
    twoLiterExemption: 'Les générateurs continus à serpentin de faible volume bénéficient d’exemptions d’opérateur sous réserve d’un numéro CRN provincial valide.',
    penalties: 'Arrêt immédiat de l’appareil, scellés et amendes prononcées par les tribunaux provinciaux.',
    specificRisk: 'Sans numéro CRN provincial valide, AUCUN appareil sous pression ne peut être exploité au Canada.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australie & Nouvelle-Zélande',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Asie-Pacifique',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343',
    bodyType: 'Organismes d’Inspection Agréés (Accréditation NATA / SafeWork)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'In-Service Inspections AU'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Annuel (12 mois) externe / 2 ans interne',
    herkeuringDetails: 'Table 4.1 de l’AS/NZS 3788 : Contrôle externe annuel et contrôle interne avec épreuve des soupapes tous les 2 ans.',
    twoLiterExemption: 'Les appareils classés Hazard Level E (risque négligeable sous AS 4343) sont exemptés de l’enregistrement auprès de l’État.',
    penalties: 'Amendes sous le WHS Act pouvant atteindre 3 000 000 AU$ pour les personnes morales en cas de violation grave.',
    specificRisk: 'L’Australie exige une procédure de « Design Registration » préalable avant toute importation.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];

export const COUNTRIES_DE: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Niederlande',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Warenwetbesluit drukapparatuur 2016 (WBDA) & Warenwetregeling drukapparatuur 2016',
    standard: 'DGRL 2014/68/EU + PRDA Katern 1.3',
    bodyType: 'NL-CBI (Konformitätsbewertungsstelle)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Prüfung vor Inbetriebnahme (KvI) → Verklaring van Ingebruikneming (VVI)',
    herkeuringTermijn: 'Alle 2 Jahre (24 Monate)',
    herkeuringDetails: 'Verpflichtende wiederkehrende Prüfung mit Sichtprüfung innen/außen, Wasserdruckprüfung, Sicherheitsventilprüfung und Wanddickenmessung nach PRDA 1.3.',
    twoLiterExemption: 'Vollständig befreit von Prüfung vor Inbetriebnahme und wiederkehrenden Prüfungen nach Art. 4 Abs. 3 DGRL (SEP). Reguläre Arbeitsschutzwartung nach Arbobesluit Art. 7.4a.',
    penalties: 'Wirtschaftsstraftat (WED Art. 1a). Niederländische Arbeitsinspektion (NLA) mit Befugnis zur sofortigen Stilllegung und Bußgeldern bis zu Zehntausenden Euro.',
    specificRisk: 'Hersteller-CE wird oft mit Betriebsgenehmigung verwechselt. Einsatz ohne VVI ist direkt strafbar.',
    operatingCertificateName: 'Verklaring van Ingebruikneming (VVI)'
  },
  {
    code: 'DE',
    name: 'Deutschland',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Betriebssicherheitsverordnung (BetrSichV) & TRBS (Technische Regeln für Betriebssicherheit)',
    standard: 'DGRL 2014/68/EU + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Zugelassene Überwachungsstelle)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Prüfung vor Inbetriebnahme (§ 15 BetrSichV) + Erlaubnispflicht (§ 18 BetrSichV)',
    herkeuringTermijn: '1 Jahr (äußere) / 3 Jahre (innere) / 6–9 Jahre (Festigkeit)',
    herkeuringDetails: 'Anhang 2 Abschnitt 4 BetrSichV: Äußere Prüfung (12 Monate), Innere Prüfung (max. 36 Monate), Festigkeitsprüfung (6 bis 9 Jahre). Für Kategorie IV ist eine behördliche Erlaubnis der Gewerbeaufsicht vorgeschrieben.',
    twoLiterExemption: 'Unter 2 Liter (Art. 4 Abs. 3 SEP): Keine erlaubnispflichtige Dampfkesselanlage. Prüfung durch zur Prüfung befähigte Person (bP) nach TRBS 1203 ohne zwingende ZÜS-Beteiligung zulässig.',
    penalties: 'Ordnungswidrigkeit (§ 22 BetrSichV) bis 100.000 € Bußgeld oder Straftat (§ 26 Chemikaliengesetz/ArbSchG) bei Gefährdung.',
    specificRisk: 'In Deutschland gilt bei Kategorie IV eine Genehmigungspflicht (Erlaubnispflicht) vor Aufstellung.',
    operatingCertificateName: 'Erlaubnis der Gewerbeaufsicht / ZÜS Prüfbescheinigung'
  },
  {
    code: 'BE',
    name: 'Belgien',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Codex über das Wohlergehen bei der Arbeit, Buch IV, Titel 3 (Arbeitsmittel)',
    standard: 'DGRL 2014/68/EU + EN 12952 / EN 13445',
    bodyType: 'EDTC (Zugelassener Technischer Überwachungsdienst)',
    bodies: ['Vinçotte', 'BTV Control', 'Apragaz', 'Bureau Veritas BE', 'OCB'],
    kviName: 'Abnahmeprüfung vor Inbetriebnahme (Codex Buch IV Art. IV.3-13)',
    herkeuringTermijn: 'Jährlich (alle 12 Monate)',
    herkeuringDetails: 'Verpflichtende jährliche Prüfung durch einen EDTC mit Sichtprüfung, Funktionsprüfung der Sicherheitsorgane und periodischer Druckprüfung.',
    twoLiterExemption: 'Unter 2 Liter: Fällt unter Art. 4 Abs. 3 DGRL. Ausgenommen vom Kesselregime des Codex. Keine EDTC-Prüfung erforderlich.',
    penalties: 'Kontrollen durch die Arbeitsinspektion (FOD WASO). Strafanzeige und sofortige Stilllegung.',
    specificRisk: 'Belgien schreibt bei über 2 Litern eine strenge jährliche Prüffrist vor.',
    operatingCertificateName: 'SECT / EDTC Prüfbescheinigung'
  },
  {
    code: 'FR',
    name: 'Frankreich',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Arrêté ministériel vom 20. November 2017 über Druckgeräte im Betrieb',
    standard: 'DGRL 2014/68/EU + CTP Chaudières',
    bodyType: 'Organisme Habilité (OH / APAVE, SOCOTEC, DEKRA, Bureau Veritas)',
    bodies: ['APAVE', 'SOCOTEC', 'Bureau Veritas France', 'DEKRA Industrial France', 'TÜV Rheinland France'],
    kviName: 'Déclaration de Mise en Service (DMS) & Contrôle de Mise en Service (CMS)',
    herkeuringTermijn: 'Wiederkehrende Prüfung: 18–24 Monate / Requalifikation: 5–10 Jahre',
    herkeuringDetails: 'Prüfung vor Inbetriebnahme (CMS), regelmäßige Inspektionen und wiederkehrende Requalifikation mit Druckprüfung.',
    twoLiterExemption: 'Unter 2 Liter: Vollständig befreit von DMS, CMS und periodischer Requalifikation nach Art. 4 Abs. 3 DGRL.',
    penalties: 'Stilllegungsverfügung durch die DREAL, Bußgelder und strafrechtliche Konsequenzen nach dem Code de l’Environnement.',
    specificRisk: 'Verpflichtende Meldung im LUNE-Portal der Regierung für Geräte > 2L vor erstem Einsatz.',
    operatingCertificateName: 'DMS Empfangsbescheinigung & CMS Nachweis'
  },
  {
    code: 'UK',
    name: 'Vereinigtes Königreich (UK)',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 / SI 2000 No. 128)',
    standard: 'UKCA / PE(S)R 2016 + BS EN 12952',
    bodyType: 'Competent Person / Prüfstellen (UKAS akkreditiert)',
    bodies: ['Allianz Engineering', 'Bureau Veritas UK', 'HSB UK', 'Zurich Engineering', 'British Engineering Services'],
    kviName: 'Written Scheme of Examination (WSE) & Vor-Betriebsprüfung',
    herkeuringTermijn: '12 bis 14 Monate (Dampfkessel)',
    herkeuringDetails: 'PSSR 2000 Regulation 8 & 9: Pflicht zur Erstellung eines Written Scheme of Examination (WSE) durch eine zertifizierte Person.',
    twoLiterExemption: 'PSSR Regulation 4: Durchlauferhitzer mit geringem Wasserinhalt ohne Dampftrommel sind weitgehend von der WSE-Kesselpflicht befreit.',
    penalties: 'Health and Safety Executive (HSE): Improvement & Prohibition Notices und gerichtliche Strafen.',
    specificRisk: 'Der Betrieb eines Dampfgeräts ohne gültiges WSE ist im UK direkt strafbar.',
    operatingCertificateName: 'Certificate of Examination under Written Scheme (WSE)'
  },
  {
    code: 'CH',
    name: 'Schweiz',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Verordnung über Druckgeräte (DGV / SR 832.312.12)',
    standard: 'DGRL 2014/68/EU + SVTI Regelwerk',
    bodyType: 'SVTI (Schweizerischer Verein für technische Inspektionen)',
    bodies: ['SVTI Kesselinspektorat', 'Kantonale Inspektorate'],
    kviName: 'SVTI Betriebsbewilligung & Kesselprüfbuch',
    herkeuringTermijn: '1 bis 2 Jahre (jährlich für befeuerte Kessel)',
    herkeuringDetails: 'Periodische Prüfung durch das SVTI: Jährliche Sicherheitsventilprüfung, innere Prüfung alle 2 bis 3 Jahre.',
    twoLiterExemption: 'MRA-Anerkennung von Art. 4 Abs. 3 DGRL. Geräte ≤ 2 Liter fallen nicht unter das SVTI-Kesselregime.',
    penalties: 'Kontrollen durch SUVA und kantonale Ämter. Sofortige Stilllegung nach UVG.',
    specificRisk: 'Strenge Grenzkontrollen durch SUVA und Schweizer Zoll bezüglich Kesselprüfbuch.',
    operatingCertificateName: 'SVTI Betriebsbewilligung / Kesselprüfbuch'
  },
  {
    code: 'US',
    name: 'Vereinigte Staaten (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'Nordamerika',
    law: 'State Boiler & Pressure Vessel Safety Acts (z. B. Texas TDLR Ch. 755, Cal/OSHA Title 8)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2)',
    bodyType: 'National Board Commissioned Inspector (Bundesstaat / AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Bureaus'],
    kviName: 'Initial Inspection & First Operating Certificate Issuance',
    herkeuringTermijn: 'Standardmäßig jährlich (alle 12 Monate)',
    herkeuringDetails: 'NBIC NB-23 Part 2: Jährliche innere und äußere Inspektion von Power Boilers mit Erteilung des Certificate of Operation.',
    twoLiterExemption: 'Ausnahme für „Coil-Type Forced Circulation Steam Generators“: Befreiung von Kesselvorschriften bei kontinuierlichem Durchlauf ohne Kesseltrommel.',
    penalties: 'Tagesbußgelder über 1.000 $, Stilllegung („Red Tagging“) und Verlust des Haftpflichtversicherungsschutzes.',
    specificRisk: 'Jeder Bundesstaat führt ein eigenes Register (State Tag). Ohne ASME-Stempel droht Beschlagnahme.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Kanada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'Nordamerika',
    law: 'Provincial Safety Codes Acts (Ontario TSSA, Alberta ABSA, BC Technical Safety)',
    standard: 'CSA B51 (Boiler, Pressure Vessel, and Pressure Piping Code)',
    bodyType: 'Provincial Safety Authorities (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Quebec)'],
    kviName: 'CRN (Canadian Registration Number) & Initial Operating Permit',
    herkeuringTermijn: 'Jährlich (alle 12 Monate) für Hochdruck-Dampfkessel',
    herkeuringDetails: 'CSA B51 und Provinzvorschriften fordern jährliche Prüfungen zur Verlängerung des Certificate of Inspection (COI).',
    twoLiterExemption: 'Kleine Durchlauf-Dampferzeuger mit geringem Wasserinhalt fallen unter Betreiber-Befreiungen bei gültiger CRN-Nummer.',
    penalties: 'Safety Orders, Versiegelung der Geräte und Gerichtsbußgelder nach dem Safety Codes Act.',
    specificRisk: 'Ohne gültige CRN-Nummer darf in Kanada KEIN Druckgerät verkauft oder betrieben werden.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australien & Neuseeland',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Asien-Pazifik',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343',
    bodyType: 'Akkreditierte Prüfstellen (NATA / SafeWork)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'In-Service Inspections'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Jährlich (12 Monate) extern / 2 Jahre intern',
    herkeuringDetails: 'AS/NZS 3788 Tabelle 4.1: Jährliche äußere Prüfung und zweijährliche innere Prüfung mit Sicherheitsventiltest.',
    twoLiterExemption: 'Geräte der Risikostufe Hazard Level E (geringes Risiko nach AS 4343) sind von der periodischen staatlichen Registrierung befreit.',
    penalties: 'SafeWork Bußgelder nach WHS Act bis zu 3.000.000 AU$ bei schweren Verstößen.',
    specificRisk: 'Australien verlangt vor Einfuhr eine behördliche „Design Registration“.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];

export function getCountryData(lang: string): CountryInfo[] {
  switch (lang) {
    case 'fr':
      return COUNTRIES_FR;
    case 'de':
      return COUNTRIES_DE;
    case 'en':
      return COUNTRIES_EN;
    case 'nl':
    default:
      return COUNTRIES_NL;
  }
}
