export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  region: 'europe' | 'north-america' | 'apac';
  regionLabel: string;
  law: string;
  standard: string;
  bodyType: string;
  bodies: string[];
  kviName: string;
  herkeuringTermijn: string;
  herkeuringDetails: string;
  twoLiterExemption: string;
  penalties: string;
  specificRisk: string;
  operatingCertificateName?: string;
}

export const COUNTRIES_NL: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Nederland',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Warenwetbesluit drukapparatuur 2016 (WBDA) & Warenwetregeling drukapparatuur 2016',
    standard: 'PED 2014/68/EU + PRDA Katern 1.3',
    bodyType: 'NL-CBI (Conformiteitsbeoordelingsinstantie)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Keuring voor Ingebruikneming (KvI) → Verklaring van Ingebruikneming (VVI)',
    herkeuringTermijn: 'Elke 2 jaar (24 maanden)',
    herkeuringDetails: 'Verplichte periodieke herkeuring met visueel inwendig/uitwendig onderzoek, hydrostatische druktest, beproeving van de veiligheidsklep en wanddiktemeting conform PRDA katern 1.3.',
    twoLiterExemption: 'Volledig vrijgesteld van KvI en herkeuring onder Artikel 4 lid 3 PED (SEP). Regulier werkgeversonderhoud conform Arbobesluit art. 7.4a.',
    penalties: 'Kwalificatie als economisch delict (WED art. 1a). Bevoegdheid Nederlandse Arbeidsinspectie (NLA) tot directe stillegging en bestuurlijke boetes tot tienduizenden euro’s.',
    specificRisk: 'Veel gebruikers verwarren fabrieks-CE met exploitatiegoedkeuring. Inzet zonder VVI is direct strafbaar.',
    operatingCertificateName: 'Verklaring van Ingebruikneming (VVI)'
  },
  {
    code: 'DE',
    name: 'Duitsland',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Betriebssicherheitsverordnung (BetrSichV) & TRBS (Technische Regeln für Betriebssicherheit)',
    standard: 'PED 2014/68/EU + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Zugelassene Überwachungsstelle)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Prüfung vor Inbetriebnahme (§ 15 BetrSichV) + Erlaubnispflicht (§ 18 BetrSichV)',
    herkeuringTermijn: '1 jaar (uitwendig) / 3 jaar (inwendig) / 6–9 jaar (druktest)',
    herkeuringDetails: 'Anhang 2 Abschnitt 4 BetrSichV: Äußere Prüfung (12 mnd), Innere Prüfung (max. 36 mnd), Festigkeitsprüfung (6 tot 9 jaar). Voor Cat. IV stoominstallaties is bovendien een officiële exploitatievergunning (Erlaubnis) van de Gewerbeaufsicht verplicht.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Geen erlaubnispflichtige stoominstallatie. Mag intern worden gekeurd door een "zur Prüfung befähigte Person" (bP) volgens TRBS 1203 zonder verplichte ZÜS-tussenkomst.',
    penalties: 'Overtreding van de BetrSichV is een Ordnungswidrigkeit (§ 22 BetrSichV) met boetes tot € 100.000,- of bij opzet/gevaarzetting een Straftat (§ 26 Chemikaliengesetz/ArbSchG).',
    specificRisk: 'In Duitsland geldt bij Categorie IV een vergunningsplicht (Erlaubnispflicht) vóór plaatsing. Zonder vergunning mag de machine de openbare weg of industriële site niet op.',
    operatingCertificateName: 'Erlaubnis der Gewerbeaufsicht / ZÜS Prüfbescheinigung'
  },
  {
    code: 'BE',
    name: 'België',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Codex over het welzijn op het werk (Boek IV, Titel 3) & KB van 18 oktober 1991 / 17 maart 2022',
    standard: 'PED 2014/68/EU + Belgische Codex',
    bodyType: 'EDTC (Externe Dienst voor Technische Controles)',
    bodies: ['Vinçotte', 'Normec BTV', 'Apragaz', 'OCB', 'Bureau Veritas BE'],
    kviName: 'Indienststellingsonderzoek door EDTC vóór eerste ingebruikname',
    herkeuringTermijn: 'Standaard jaarlijks (elke 12 maanden)',
    herkeuringDetails: 'Jaarlijks uitwendig onderzoek en verificatie van de afstelling van veiligheidskleppen. Periodiek inwendig onderzoek (verlengbaar onder strikte voorwaarden mits goedkeuring toezichthoudend ambtenaar voor stoomgeneratoren van de 4e groep).',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Vrijgesteld van specifieke stoomketel-keuring door EDTC. Valt onder algemene risicoanalyse en periodieke controle van arbeidsmiddelen.',
    penalties: 'Toezicht door FOD Werkgelegenheid, Arbeid en Sociaal Overleg (FOD WASO / Toezicht op het Welzijn op het Werk). Boetes en strafsancties via het Sociaal Strafwetboek.',
    specificRisk: 'België hanteert een zeer strikte jaarlijkse controle op stoomgeneratoren. Nederlandse bedrijven die in Vlaanderen of Wallonië werken worden hier frequent op aangesproken.',
    operatingCertificateName: 'EDTC Indienststellingsverslag & Jaarlijks Keuringsverslag'
  },
  {
    code: 'LU',
    name: 'Luxemburg',
    flag: '🇱🇺',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Règlement grand-ducal du 23 décembre 1999 (appareils à vapeur et à gaz) & Code du Travail (Livre III)',
    standard: 'PED 2014/68/EU + ITM-voorschriften',
    bodyType: 'Organisme Agréé (erkend keuringsorganisme)',
    bodies: ['Luxcontrol S.A.', 'TÜV Rheinland Luxembourg', 'APAVE Luxembourg', 'SGS Luxembourg'],
    kviName: 'Réception avant mise en service & Verplichte aanmelding ITM',
    herkeuringTermijn: 'Periodiek conform ITM-termijnen (elke 12-24 maanden)',
    herkeuringDetails: 'Keuring van de drukontlasting, veiligheidskleppen, afblazen en wanddikte. Verplichte registratie in het centrale ITM-veiligheidsdossier.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP / Sound Engineering Practice): Vrijgesteld van het zware ITM-registratiedossier en de formele réception avant mise en service.',
    penalties: 'Toezicht door de Inspection du Travail et des Mines (ITM). Bevoegdheid tot directe stillegging (arrêt immédiat), verzegeling ter plaatse en strafrechtelijke vervolging.',
    specificRisk: 'In Luxemburg treden ITM-inspecteurs streng op. Zonder goedgekeurd dossier van een erkend controleorganisme (zoals Luxcontrol) mag de machine niet op de werf worden ingezet.',
    operatingCertificateName: 'Rapport de réception ITM / Certificat de contrôle périodique'
  },
  {
    code: 'FR',
    name: 'Frankrijk',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europa',
    law: 'Arrêté du 20 novembre 2017 relatif au suivi en service des ESP & Code de l\'environnement',
    standard: 'PED 2014/68/EU + CODAP / CTP',
    bodyType: 'Organisme Habilité (OH)',
    bodies: ['APAVE', 'Bureau Veritas France', 'DEKRA Industrial FR', 'SOCOTEC', 'CETIM'],
    kviName: 'Contrôle de mise en service (CMS) & Déclaration de mise en service (DMS)',
    herkeuringTermijn: 'Elke 2 jaar (24 maanden) IP / 10 jaar RP',
    herkeuringDetails: 'Inspection périodique (IP) uiterlijk elke 24 maanden voor "générateurs de vapeur". Requalification périodique (RP) met hydraulische herkeuring elke 10 jaar.',
    twoLiterExemption: 'Onder 2 liter (Art. 4.3 SEP): Uitdrukkelijk vrijgesteld van Déclaration de mise en service en periodieke inspecties door Organismes Habilités.',
    penalties: 'Handhaving door de DREAL / Inspection du travail. Overtredingen vallen onder het Code de l\'environnement met zware administratieve en strafrechtelijke sancties.',
    specificRisk: 'Zonder voorafgaande "Déclaration de mise en service" via het Franse overheidsloket LUNE mag een Categorie IV installatie niet operationeel worden gebruikt.',
    operatingCertificateName: 'Récépissé de Déclaration de Mise en Service (DMS) via LUNE'
  },
  {
    code: 'UK',
    name: 'Verenigd Koninkrijk',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europa (Non-EU)',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 - Statutory Instrument 2000 No. 168)',
    standard: 'PER 2016 / UKCA + SAFed Guidelines',
    bodyType: 'Competent Person (SAFed Accredited Inspection Bodies)',
    bodies: ['Allianz Engineering', 'Zurich Engineering', 'Bureau Veritas UK', 'British Engineering Services', 'TÜV SÜD UK'],
    kviName: 'Written Scheme of Examination (WSE) + Initial Inspection',
    herkeuringTermijn: 'Elke 12 tot 14 maanden (Jaarlijks)',
    herkeuringDetails: 'PSSR regels vereisen dat stoominstallaties worden gekeurd volgens een formeel Written Scheme of Examination (WSE). Voor stoomtoestellen wordt de intervaltermijn nagenoeg universeel vastgelegd op 12 tot 14 maanden door de Competent Person.',
    twoLiterExemption: 'Voor SEP / kleine volumes (onder 250 bar-liter of waterinhoud onder drempelwaarden) geldt geen verplichting voor een complex stoomketel-WSE.',
    penalties: 'Handhaving door de Health and Safety Executive (HSE) onder de Health and Safety at Work Act 1974; Improvement en Prohibition Notices met onbeperkte boetes.',
    specificRisk: 'Werken in het VK met mobiele stoomcleaners vereist voorafgaande validatie van het WSE door een Britse Competent Person.',
    operatingCertificateName: 'Certificate of Examination under WSE'
  },
  {
    code: 'CH',
    name: 'Zwitserland',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europa (Non-EU)',
    law: 'SR 832.30 (VUV - Unfallverhütungsverordnung) & EKAS Richtlinie 6516 (Druckbehälter)',
    standard: 'MRA EU-CH (PED 2014/68/EU equivalent) + SVTI Vorschriften',
    bodyType: 'SVTI / ASIT (Schweizerischer Verein für technische Inspektionen)',
    bodies: ['SVTI Kesselinspektorat', 'SUVA (Schweizerische Unfallversicherung)', 'DEKRA Schweiz'],
    kviName: 'Erstprüfung und Bewilligung zur Inbetriebnahme durch das SVTI Kesselinspektorat',
    herkeuringTermijn: '1 tot 2 jaar (jaarlijks voor gestookte stoomketels)',
    herkeuringDetails: 'Gestookte stoomketels en stoomgeneratoren worden periodiek geïnspecteerd door het SVTI Kesselinspektorat. Uitwendige inspectie en veiligheidskleppen jaarlijks; inwendig elke 2 tot 3 jaar.',
    twoLiterExemption: 'Via de bilaterale akkoorden (MRA) erkent Zwitserland PED Art. 4 lid 3 (Gute Ingenieurpraxis). Toestellen onder 2 liter vallen buiten de verplichte SVTI-kesselkeuringen.',
    penalties: 'Controles door SUVA en kantonale arbeidsinspecties. Stillegging en boetes conform het Zwitserse Unfallversicherungsgesetz (UVG).',
    specificRisk: 'Zwitserse douane en SUVA controleren streng bij de grens en op bouwlocaties op het SVTI-keuringsboek.',
    operatingCertificateName: 'SVTI Betriebsbewilligung / Kesselprüfbuch'
  },
  {
    code: 'US',
    name: 'Verenigde Staten (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'Noord-Amerika',
    law: 'State Boiler & Pressure Vessel Safety Acts (bijv. Texas TDLR Ch. 755, Cal/OSHA Title 8, Ohio BBS, NY DOL)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2: Inspection)',
    bodyType: 'National Board Commissioned Inspector (State / Authorized Insurance AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Inspection Bureaus'],
    kviName: 'Initial Inspection & First Operating Certificate Issuance (State Boiler Division)',
    herkeuringTermijn: 'Standaard jaarlijks (elke 12 maanden)',
    herkeuringDetails: 'NBIC NB-23 Part 2 (In-service Inspection) & staatsstatuut vereisen een jaarlijkse externe en interne inspectie van "Power Boilers" (stoom > 15 psi of water > 160 psi / 250°F). Bevat afdichting van het ASME/NB UV-veiligheidsventiel en uitgifte van een nieuw Certificate of Operation.',
    twoLiterExemption: 'Uitzonderingen via "Coil-Type Forced Circulation Steam Generators without a Drum": De meeste staten (en ASME Sec. I PEB/PMB) stellen doorstroom-branders/warmtewisselaars met spiraal vrij van de zware ketel-inspectie mits de waterinhoud van de spiraal onder statelijke drempels blijft (vaak < 5 US gallons / ~19 liter, of miniatuurketels < 16 inch diameter). Daarboven geldt direct de jaarlijkse staatskeuring.',
    penalties: 'Exploitatie zonder geldig "Certificate of Operation" is een misdrijf/overtreding onder State Labor Codes. Boetes tot $1.000+ per dag, rode vergrendeling ("Red Tagging") en direct vervallen van de aansprakelijkheidsdekking bij claims.',
    specificRisk: 'Elke Amerikaanse staat heeft zijn eigen Chief Boiler Inspector en staatsnummering (State Tag). Wie met Europese apparatuur in de VS werkt zonder ASME-stempel en National Board registratie loopt het risico op directe inbeslagname.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'Noord-Amerika',
    law: 'Provincial Safety Codes Acts (Ontario TSSA O. Reg. 220/01, Alberta ABSA AB-506, BC Technical Safety)',
    standard: 'CSA B51 (Boiler, Pressure Vessel, and Pressure Piping Code)',
    bodyType: 'Provincial Safety Authorities (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Quebec)'],
    kviName: 'CRN (Canadian Registration Number) Verificatie & Initial Operating Permit',
    herkeuringTermijn: 'Jaarlijks (elke 12 maanden) voor High-Pressure Boilers',
    herkeuringDetails: 'CSA B51 en provinciale verordeningen (zoals TSSA Act) leggen vast dat hogedrukstoomketels jaarlijks gekeurd moeten worden om het Certificate of Inspection (COI) te verlengen. Overige drukvaten volgen een 3- tot 5-jarige cyclus.',
    twoLiterExemption: 'Kleine branders/warmtewisselaars van het spoeltype ("Coil type steam generators") met beperkte waterinhoud (< 3 tot 5 gallons afhankelijk van de provincie) vallen onder vrijstellingen voor stoomketeloperators, mits de drukdelen een geldig Canadees Registratienummer (CRN) bezitten.',
    penalties: 'Provincial Safety Orders, onmiddellijke verzegeling van de apparatuur en gerechtelijke boetes via provinciale rechtbanken conform de Safety Codes Act.',
    specificRisk: 'Zonder geldig provinciaal CRN-nummer mag in Canada GEEN ENKEL drukvat worden verkocht of in werking gesteld, ongeacht CE- of ASME-certificering.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australië & Nieuw-Zeeland',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Azië-Pacific',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria, SafeWork QLD)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343 (Hazard Levels)',
    bodyType: 'Competent In-Service Inspection Bodies (NATA Accredited / SafeWork Recognised)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'Heng Sheng / In-Service Inspections'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Jaarlijks (12 mnd) extern / 2 jaar inwendig voor gestookte stoomketels',
    herkeuringDetails: 'Tabel 4.1 van AS/NZS 3788 schrijft voor gestookte stoomgeneratoren van Hazard Level A, B en C een jaarlijkse externe inspectie voor en minimaal tweejaarlijkse inwendige inspecties met afpersen van overdrukinrichtingen.',
    twoLiterExemption: 'Apparatuur geclassificeerd als Hazard Level E (zeer laag risico op grond van AS 4343, waar volume en druk onder de drempelwaarden vallen) is vrijgesteld van periodieke registratie bij de staat.',
    penalties: 'Handhaving door SafeWork. Hoge boetes onder de WHS Act (tot AU$ 3.000.000,- voor rechtspersonen bij ernstige veiligheidsovertredingen).',
    specificRisk: 'Australië vereist voorafgaande "Design Registration" bij de staatsautoriteit voordat een stoomtoestel het land in mag.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];

export const COUNTRIES_EN: CountryInfo[] = [
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Commodities Act Decree on Pressure Equipment 2016 (WBDA 2016) & Commodities Act Regulation',
    standard: 'PED 2014/68/EU + PRDA Section 1.3',
    bodyType: 'NL-CBI (Conformity Assessment Body)',
    bodies: ['TÜV NORD Nederland', 'DEKRA Industrial', 'Kiwa', 'Bureau Veritas NL', 'SGS'],
    kviName: 'Pre-Commissioning Inspection (KvI) → Declaration of In-Service Authorization (VVI)',
    herkeuringTermijn: 'Every 2 years (24 months)',
    herkeuringDetails: 'Mandatory periodic recertification with internal and external visual examination, hydrostatic pressure test, safety relief valve bench testing, and ultrasonic wall thickness measurements under PRDA Section 1.3.',
    twoLiterExemption: 'Fully exempt from pre-commissioning examination (KvI) and periodic recertification under Article 4(3) PED (SEP). Standard employer workplace safety maintenance applies (Working Conditions Decree art. 7.4a).',
    penalties: 'Classified as an economic offence (Economic Offences Act Art. 1a). The Netherlands Labour Inspectorate (NLA) has authority for immediate operational stop-work orders and administrative fines up to tens of thousands of euros.',
    specificRisk: 'Many operators confuse manufacturer CE marking with operational in-service authorization. Operating Category IV equipment without a valid VVI is a direct statutory offence.',
    operatingCertificateName: 'Declaration of In-Service Authorization (VVI)'
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Industrial Safety Regulation (Betriebssicherheitsverordnung - BetrSichV) & TRBS Rules',
    standard: 'PED 2014/68/EU + AD 2000 / EN 12952',
    bodyType: 'ZÜS (Approved Inspection Body)',
    bodies: ['TÜV SÜD', 'TÜV Rheinland', 'TÜV NORD', 'DEKRA Automobil/Industrial', 'GTÜ'],
    kviName: 'Pre-commissioning Inspection (§ 15 BetrSichV) + Mandatory Operating Permit (§ 18 BetrSichV)',
    herkeuringTermijn: '1 year (external) / 3 years (internal) / 6–9 years (strength test)',
    herkeuringDetails: 'Annex 2 Section 4 BetrSichV: External audit (12 months), Internal inspection (max. 36 months), Strength/hydrostatic test (6 to 9 years). Category IV steam assemblies also require an official operating permit (Erlaubnis) from the Trade Supervisory Authority (Gewerbeaufsicht).',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Not an installation subject to mandatory permit (Erlaubnis). Can be inspected in-house by an authorized competent person (zur Prüfung befähigte Person - bP) in accordance with TRBS 1203 without mandatory ZÜS involvement.',
    penalties: 'Violation of BetrSichV constitutes an administrative offence (§ 22 BetrSichV) with fines up to € 100,000, or a criminal offence in cases of intent or endangerment (§ 26 ChemG / ArbSchG).',
    specificRisk: 'In Germany, Category IV requires an official operating permit (Erlaubnispflicht) before installation. Without a permit, the machine may not be deployed on public roads or industrial sites.',
    operatingCertificateName: 'Gewerbeaufsicht Operating Permit / ZÜS Inspection Certificate'
  },
  {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Code of Well-being at Work (Book IV, Title 3) & Royal Decrees of 18 Oct 1991 / 17 Mar 2022',
    standard: 'PED 2014/68/EU + Belgian Code of Well-being',
    bodyType: 'EDTC (External Service for Technical Controls)',
    bodies: ['Vinçotte', 'Normec BTV', 'Apragaz', 'OCB', 'Bureau Veritas BE'],
    kviName: 'Commissioning examination by an accredited EDTC prior to first operation',
    herkeuringTermijn: 'Standard annual (every 12 months)',
    herkeuringDetails: 'Annual external examination and calibration verification of safety relief valves. Periodic internal examination (extendable under strict conditions with supervisory authority approval for 4th group steam generators).',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Exempt from specific steam boiler inspection by an EDTC. Governed by general risk assessment and periodic work equipment checks.',
    penalties: 'Supervised by the FPS Employment, Labour and Social Dialogue (FPS WASO). Substantial administrative and criminal penalties under the Social Penal Code.',
    specificRisk: 'Belgium enforces a strict annual inspection regime for steam generators. Cross-border contractors from neighboring countries are frequently audited.',
    operatingCertificateName: 'EDTC Commissioning Report & Annual Inspection Certificate'
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    flag: '🇱🇺',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Grand-Ducal Regulation of 23 Dec 1999 (Steam & Gas Appliances) & Labour Code (Book III)',
    standard: 'PED 2014/68/EU + ITM Requirements',
    bodyType: 'Organisme Agréé (Accredited Inspection Body)',
    bodies: ['Luxcontrol S.A.', 'TÜV Rheinland Luxembourg', 'APAVE Luxembourg', 'SGS Luxembourg'],
    kviName: 'Pre-commissioning acceptance (Réception avant mise en service) & Mandatory ITM notification',
    herkeuringTermijn: 'Periodic per ITM schedule (every 12–24 months)',
    herkeuringDetails: 'Examination of pressure relief systems, safety valves, venting lines, and wall thickness. Mandatory registration in the central ITM safety registry.',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Exempt from heavy ITM dossier registration and formal pre-commissioning acceptance (réception avant mise en service).',
    penalties: 'Enforced by the Inspectorate of Labour and Mines (ITM). Authority for immediate stop-work orders (arrêt immédiat), on-site sealing, and judicial prosecution.',
    specificRisk: 'ITM inspectors enforce strict compliance in Luxembourg. Without an approved dossier from an accredited inspection body (such as Luxcontrol), equipment cannot be deployed on job sites.',
    operatingCertificateName: 'ITM Acceptance Report / Periodic Inspection Certificate'
  },
  {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    region: 'europe',
    regionLabel: 'Europe',
    law: 'Decree of 20 November 2017 on In-Service Monitoring of Pressure Equipment & Environmental Code',
    standard: 'PED 2014/68/EU + CODAP / CTP',
    bodyType: 'Organisme Habilité (OH - Authorized Inspection Body)',
    bodies: ['APAVE', 'Bureau Veritas France', 'DEKRA Industrial FR', 'SOCOTEC', 'CETIM'],
    kviName: 'Commissioning Control (CMS) & Commissioning Declaration (DMS via LUNE)',
    herkeuringTermijn: 'Every 2 years (24 months) for IP / 10 years for RP',
    herkeuringDetails: 'Periodic inspection (IP) at least every 24 months for "steam generators". Periodic requalification (RP) including hydraulic pressure testing every 10 years.',
    twoLiterExemption: 'Under 2 litres (Art. 4.3 SEP): Expressly exempt from Commissioning Declaration (DMS) and periodic inspections by Authorized Bodies (Organismes Habilités).',
    penalties: 'Enforcement by DREAL / Labour Inspectorate. Violations fall under the Environmental Code with severe administrative and criminal sanctions.',
    specificRisk: 'Without prior Commissioning Declaration (DMS) registered via the French government portal LUNE, Category IV equipment cannot be operated legally.',
    operatingCertificateName: 'Receipt of Commissioning Declaration (DMS) via LUNE'
  },
  {
    code: 'UK',
    name: 'United Kingdom',
    flag: '🇬🇧',
    region: 'europe',
    regionLabel: 'Europe (Non-EU)',
    law: 'Pressure Systems Safety Regulations 2000 (PSSR 2000 - Statutory Instrument 2000 No. 168)',
    standard: 'PER 2016 / UKCA + SAFed Guidelines',
    bodyType: 'Competent Person (SAFed Accredited Inspection Bodies)',
    bodies: ['Allianz Engineering', 'Zurich Engineering', 'Bureau Veritas UK', 'British Engineering Services', 'TÜV SÜD UK'],
    kviName: 'Written Scheme of Examination (WSE) + Initial Inspection',
    herkeuringTermijn: 'Every 12 to 14 months (Annual)',
    herkeuringDetails: 'PSSR regulations require steam installations to be examined in accordance with a formal Written Scheme of Examination (WSE). For steam equipment, the interval is almost universally established at 12 to 14 months by the Competent Person.',
    twoLiterExemption: 'For SEP / micro-volumes (under 250 bar-litres or below water volume thresholds), there is no statutory obligation for a complex steam boiler WSE.',
    penalties: 'Enforcement by the Health and Safety Executive (HSE) under the Health and Safety at Work etc. Act 1974; Improvement and Prohibition Notices with unlimited fines.',
    specificRisk: 'Operating mobile steam cleaners in the UK requires prior validation of the WSE by a UK certified Competent Person.',
    operatingCertificateName: 'Certificate of Examination under WSE'
  },
  {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    region: 'europe',
    regionLabel: 'Europe (Non-EU)',
    law: 'SR 832.30 (VUV - Accident Prevention Ordinance) & EKAS Guideline 6516 (Pressure Vessels)',
    standard: 'MRA EU-CH (PED 2014/68/EU equivalent) + SVTI Regulations',
    bodyType: 'SVTI / ASIT (Swiss Association for Technical Inspections)',
    bodies: ['SVTI Boiler Inspectorate', 'SUVA (Swiss National Accident Insurance)', 'DEKRA Switzerland'],
    kviName: 'Initial inspection and operating permit by the SVTI Boiler Inspectorate',
    herkeuringTermijn: '1 to 2 years (annual for fired steam boilers)',
    herkeuringDetails: 'Fired steam boilers and steam generators are periodically inspected by the SVTI Boiler Inspectorate. External inspection and safety relief valve testing annually; internal inspection every 2 to 3 years.',
    twoLiterExemption: 'Under bilateral agreements (MRA), Switzerland recognizes PED Art. 4(3) (Sound Engineering Practice). Units under 2 litres fall outside mandatory SVTI boiler audits.',
    penalties: 'Inspections by SUVA and cantonal labor inspectorates. Shutdown and fines under the Swiss Accident Insurance Act (UVG).',
    specificRisk: 'Swiss customs and SUVA strictly verify the SVTI boiler inspection logbook at the border and on construction sites.',
    operatingCertificateName: 'SVTI Operating Permit / Boiler Inspection Logbook'
  },
  {
    code: 'US',
    name: 'United States (USA)',
    flag: '🇺🇸',
    region: 'north-america',
    regionLabel: 'North America',
    law: 'State Boiler & Pressure Vessel Safety Acts (e.g., Texas TDLR Ch. 755, Cal/OSHA Title 8, Ohio BBS, NY DOL)',
    standard: 'ASME BPVC (Sec. I & VIII) + NBIC (NB-23 Part 2: Inspection)',
    bodyType: 'National Board Commissioned Inspector (State / Authorized Insurance AIA)',
    bodies: ['Hartford Steam Boiler (HSB)', 'FM Global', 'Travelers BoilerRe', 'Zurich Services', 'State Boiler Inspection Bureaus'],
    kviName: 'Initial Inspection & First Operating Certificate Issuance (State Boiler Division)',
    herkeuringTermijn: 'Standard annual (every 12 months)',
    herkeuringDetails: 'NBIC NB-23 Part 2 (In-service Inspection) & state statutes require annual external and internal inspection of "Power Boilers" (steam > 15 psi or water > 160 psi / 250°F). Includes testing/sealing of ASME/NB UV safety relief valves and issuance of a new Certificate of Operation.',
    twoLiterExemption: 'Exemption via "Coil-Type Forced Circulation Steam Generators without a Drum": Most states (and ASME Sec. I PEB/PMB) exempt continuous-flow coil cleaners from heavy boiler inspection provided water volume remains below state thresholds (often < 5 US gallons / ~19 litres, or miniature boilers < 16" dia). Exceeding this triggers annual state inspection.',
    penalties: 'Operating without a valid "Certificate of Operation" is a misdemeanor/violation under State Labor Codes. Fines up to $1,000+ per day, "Red Tagging" (lockout), and immediate invalidation of liability coverage.',
    specificRisk: 'Each US state has its own Chief Boiler Inspector and state numbering system (State Tag). Deploying European equipment in the US without ASME stamp and National Board registration risks immediate seizure.',
    operatingCertificateName: 'Certificate of Inspection / Certificate of Operation'
  },
  {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'north-america',
    regionLabel: 'North America',
    law: 'Provincial Safety Codes Acts (Ontario TSSA O. Reg. 220/01, Alberta ABSA AB-506, BC Technical Safety)',
    standard: 'CSA B51 (Boiler, Pressure Vessel, and Pressure Piping Code)',
    bodyType: 'Provincial Safety Authorities (TSSA / ABSA / Technical Safety BC) & AIA',
    bodies: ['TSSA (Ontario)', 'ABSA (Alberta)', 'Technical Safety BC', 'TSASK (Saskatchewan)', 'RBQ (Quebec)'],
    kviName: 'CRN (Canadian Registration Number) Verification & Initial Operating Permit',
    herkeuringTermijn: 'Annual (every 12 months) for High-Pressure Boilers',
    herkeuringDetails: 'CSA B51 and provincial regulations (such as TSSA Act) mandate annual inspections for high-pressure steam boilers to renew the Certificate of Inspection (COI). Other pressure vessels follow 3- to 5-year cycles.',
    twoLiterExemption: 'Small coil-type steam generators with limited water volume (< 3 to 5 gallons depending on province) fall under operator exemptions, provided pressure parts possess a valid Canadian Registration Number (CRN).',
    penalties: 'Provincial Safety Orders, immediate equipment sealing, and judicial fines via provincial courts under the Safety Codes Act.',
    specificRisk: 'Without a valid provincial CRN, NO pressure vessel may be sold or operated in Canada, regardless of CE or ASME certification.',
    operatingCertificateName: 'Certificate of Inspection (COI) / Operating Permit'
  },
  {
    code: 'AU',
    name: 'Australia & New Zealand',
    flag: '🇦🇺',
    region: 'apac',
    regionLabel: 'Asia-Pacific',
    law: 'Work Health and Safety (WHS) Regulations (SafeWork NSW, WorkSafe Victoria, SafeWork QLD)',
    standard: 'AS/NZS 3788 (Pressure equipment — In-service inspection) & AS 4343 (Hazard Levels)',
    bodyType: 'Competent In-Service Inspection Bodies (NATA Accredited / SafeWork Recognised)',
    bodies: ['Bureau Veritas Australia', 'SGS Australia', 'TÜV Rheinland Australia', 'Heng Sheng / In-Service Inspections'],
    kviName: 'Design Registration + Item Registration & Pre-commissioning Inspection',
    herkeuringTermijn: 'Annual (12 mos) external / 2 years internal for fired steam boilers',
    herkeuringDetails: 'Table 4.1 of AS/NZS 3788 prescribes annual external inspections and at least biennial internal inspections with pressure relief testing for Hazard Level A, B, and C fired steam generators.',
    twoLiterExemption: 'Equipment classified as Hazard Level E (negligible risk under AS 4343, where volume and pressure fall below thresholds) is exempt from periodic state registration.',
    penalties: 'Enforcement by SafeWork. Heavy fines under the WHS Act (up to AU$ 3,000,000 for corporations for category 1 safety offences).',
    specificRisk: 'Australia requires prior "Design Registration" with state authorities before any steam appliance can enter the country.',
    operatingCertificateName: 'Plant Registration Certificate & In-Service Certificate'
  }
];
